baseurl: https://kent64.github.io/blog/
languageCode: en-us
title: blog
theme: hugo-lithium-theme
ignoreFiles: ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]
publishDir: docs
enableEmoji: true
googleAnalytics: ''
disqusShortname: ''
disableKinds:
  - taxonomy
  - taxonomyTerm
  - section
  - '404'
permalinks:
  page: /:title/
  post: /:year/:month/:day/:title/
menu:
  main:
    - name: About
      url: /about/
    - name: GitHub
      url: 'https://github.com/kent64/blog'
    # - name: Twitter
    #   url: ''
params:
  description: ''
  favicon: favicon.ico
  icon:
    url: favicon.ico
  logo:
    alt: Logo
    height: 50
    url: logo.png
    width: 50
  mainSections: post

markup:
  goldmark:
    renderer:
      unsafe: true
      
