<!DOCTYPE html>
<html>
  <head>
    <title>Secondary School Student Performance</title>
    <meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta http-equiv="X-UA-Compatible" content="ie=edge" />


<link rel="stylesheet" href="/blog/assets/css/bootstrap.min.css"/>
<link rel="stylesheet" href="/blog/assets/css/layouts/main.css"/>
<link rel="stylesheet" href="/blog/assets/css/style.css"/>
<link rel="stylesheet" href="/blog/assets/css/navigators/navbar.css"/>


<link href="https://fonts.googleapis.com/css2?family=Muli:wght@300;400;500;600" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" />


<link rel="icon" type="image/png" href="/blog/images/site/favicon.png" />


<link rel="stylesheet" href="/blog/assets/css/style.css"/>

    
<meta name="description" content="Secondary School Student Performance" />
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.1.2/styles/school-book.min.css"
/>
<link rel="stylesheet" href="/blog/assets/css/layouts/single.css"/>
<link rel="stylesheet" href="/blog/assets/css/navigators/sidebar.css">


    
    
      
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
	ga('create', 'UA-XXXXXXXXX-X', 'auto');
	
	ga('send', 'pageview');
}
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>

    
  </head>

  <body data-spy="scroll" data-target="#TableOfContents" data-offset="80">
    <div class="container-fluid bg-dimmed wrapper">
      
      
    


  


  


<nav class="navbar navbar-expand-xl top-navbar final-navbar shadow">
  <div class="container">
      <button class="navbar-toggler navbar-light" id="sidebar-toggler" type="button" onclick="toggleSidebar()">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="/blog">
      <img src="/blog/images/site/main-logo.png">my ePortfolio</a>
    <button class="navbar-toggler navbar-light" id="toc-toggler" type="button" onclick="toggleTOC()">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse lang-selector" id="top-nav-items">
      <ul class="navbar-nav ml-auto">
      
      </ul>
    </div>
  </div>
  
  <img src="/blog/images/site/main-logo.png" class="d-none" id="main-logo">
  <img src="/blog/images/site/inverted-logo.png" class="d-none" id="inverted-logo">
</nav>



      
      
  <section class="sidebar-section" id="sidebar-section">
    
  </section>


      
      
<section class="content-section" id="content-section">
  <div class="content">
    <div class="container p-0 read-area">
      
      <div class="hero-area col-sm-12" id="hero-area" style='background-image: url(/blog/images/site/school.jpg);'>
      </div>

      
      <div class="page-content">
        <div class="author-profile ml-auto align-self-lg-center">
          <img class="rounded-circle" src='/blog/images/author/brendan.png'/>
          <h5 class="author-name">Hi, I&#39;m Brendan</h5>
          <p>November 1, 2020</p>
        </div>

        <div class="title">
          <h1>Secondary School Student Performance</h1>
        </div>

        <div class="post-content" id="post-content">
          <h1 id="introduction">Introduction</h1>
<p>I am writing this blog as part of an assignment. My Details:</p>
<table>
<thead>
<tr>
<th></th>
<th></th>
</tr>
</thead>
<tbody>
<tr>
<td>Student Name:</td>
<td>B Kent</td>
</tr>
<tr>
<td>Student Number:</td>
<td>cxxxxxxxx</td>
</tr>
<tr>
<td>Programme Code:</td>
<td>TU060</td>
</tr>
<tr>
<td>Version R:</td>
<td>R version 4.0.3 (2020-10-10)</td>
</tr>
<tr>
<td>R packages:</td>
<td></td>
</tr>
</tbody>
</table>
<h1 id="getting-started">Getting started</h1>
<p>We explore a student exam performance data set. This is a data set about secondary school academical achievements in Portugal. The data contains two set of results, one set for results in Maths and one set for results in Portuguese. These are merged together to form one data set which I will endeavor to break down in order to learn about the basic properties of statistics, describing the Frequency and probabilities, hypothesis testing, Normality, Missing data, Relationships, Component Analysis and more.</p>
<p>This data set is from a paper by P.Cortez and A. Silva entitled “Using Data Mining to Predict Secondary School Student Performance”. (Cortez and Silva <a href="#ref-cortez2008using">2008</a>)</p>
<p>We need to get the data</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(<span style="color:#e6db74">&#34;dplyr&#34;</span>)
</code></pre></div><pre><code>## 
## Attaching package: 'dplyr'

## The following objects are masked from 'package:stats':
## 
##     filter, lag

## The following objects are masked from 'package:base':
## 
##     intersect, setdiff, setequal, union
</code></pre>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(<span style="color:#e6db74">&#34;finalfit&#34;</span>) <span style="color:#75715e"># for ff_glimpse(studentdf)</span>
<span style="color:#a6e22e">library</span>(<span style="color:#e6db74">&#34;gridExtra&#34;</span>) <span style="color:#75715e"># for plots in a grid</span>
</code></pre></div><pre><code>## 
## Attaching package: 'gridExtra'

## The following object is masked from 'package:dplyr':
## 
##     combine
</code></pre>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(<span style="color:#e6db74">&#34;ggplot2&#34;</span>) <span style="color:#75715e"># For creating histograms and plots</span>
<span style="color:#75715e">#download.file(url=&#34;https://archive.ics.uci.edu/ml/machine-learning-databases/00320/student.zip&#34;, destfile=&#34;student.zip&#34;)</span>
<span style="color:#75715e">#unzip(&#34;student.zip&#34;,exdir = &#34;studentdf&#34;)</span>
<span style="color:#a6e22e">list.files</span>(<span style="color:#e6db74">&#34;studentdf&#34;</span>)
</code></pre></div><pre><code>## [1] &quot;student-mat.csv&quot; &quot;student-merge.R&quot; &quot;student-por.csv&quot; &quot;student.txt&quot;
</code></pre>
<p>data set description: <a href="https://archive.ics.uci.edu/ml/datasets/student+performance#">https://archive.ics.uci.edu/ml/datasets/student+performance#</a> or <a href="/blog/description/">here</a></p>
<p>read in the data</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">matdf<span style="color:#f92672">=</span><span style="color:#a6e22e">read.table</span>(<span style="color:#e6db74">&#34;studentdf/student-mat.csv&#34;</span>,sep<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;;&#34;</span>,header<span style="color:#f92672">=</span><span style="color:#66d9ef">TRUE</span>, stringsAsFactors<span style="color:#f92672">=</span><span style="color:#66d9ef">TRUE</span>)
pordf<span style="color:#f92672">=</span><span style="color:#a6e22e">read.table</span>(<span style="color:#e6db74">&#34;studentdf/student-por.csv&#34;</span>,sep<span style="color:#f92672">=</span><span style="color:#e6db74">&#34;;&#34;</span>,header<span style="color:#f92672">=</span><span style="color:#66d9ef">TRUE</span>, stringsAsFactors<span style="color:#f92672">=</span><span style="color:#66d9ef">TRUE</span>)

studentdf<span style="color:#f92672">=</span><span style="color:#a6e22e">merge</span>(x<span style="color:#f92672">=</span>matdf,y<span style="color:#f92672">=</span>pordf,by<span style="color:#f92672">=</span><span style="color:#a6e22e">c</span>(<span style="color:#e6db74">&#34;school&#34;</span>,<span style="color:#e6db74">&#34;sex&#34;</span>,<span style="color:#e6db74">&#34;age&#34;</span>,<span style="color:#e6db74">&#34;address&#34;</span>,<span style="color:#e6db74">&#34;famsize&#34;</span>,<span style="color:#e6db74">&#34;Pstatus&#34;</span>,<span style="color:#e6db74">&#34;Medu&#34;</span>,<span style="color:#e6db74">&#34;Fedu&#34;</span>,<span style="color:#e6db74">&#34;Mjob&#34;</span>,<span style="color:#e6db74">&#34;Fjob&#34;</span>,<span style="color:#e6db74">&#34;reason&#34;</span>,<span style="color:#e6db74">&#34;nursery&#34;</span>,<span style="color:#e6db74">&#34;internet&#34;</span>))
<span style="color:#a6e22e">colnames</span>(studentdf) <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">tolower</span>(<span style="color:#a6e22e">colnames</span>(studentdf))
<span style="color:#a6e22e">nrow</span>(studentdf)
</code></pre></div><pre><code>[1] 382
</code></pre>
<p>So we have 382 records in our data set.</p>
<p>Let’s see what variables we have in each record.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">colnames</span>(studentdf)
</code></pre></div><pre><code>##  [1] &quot;school&quot;       &quot;sex&quot;          &quot;age&quot;          &quot;address&quot;      &quot;famsize&quot;     
##  [6] &quot;pstatus&quot;      &quot;medu&quot;         &quot;fedu&quot;         &quot;mjob&quot;         &quot;fjob&quot;        
## [11] &quot;reason&quot;       &quot;nursery&quot;      &quot;internet&quot;     &quot;guardian.x&quot;   &quot;traveltime.x&quot;
## [16] &quot;studytime.x&quot;  &quot;failures.x&quot;   &quot;schoolsup.x&quot;  &quot;famsup.x&quot;     &quot;paid.x&quot;      
## [21] &quot;activities.x&quot; &quot;higher.x&quot;     &quot;romantic.x&quot;   &quot;famrel.x&quot;     &quot;freetime.x&quot;  
## [26] &quot;goout.x&quot;      &quot;dalc.x&quot;       &quot;walc.x&quot;       &quot;health.x&quot;     &quot;absences.x&quot;  
## [31] &quot;g1.x&quot;         &quot;g2.x&quot;         &quot;g3.x&quot;         &quot;guardian.y&quot;   &quot;traveltime.y&quot;
## [36] &quot;studytime.y&quot;  &quot;failures.y&quot;   &quot;schoolsup.y&quot;  &quot;famsup.y&quot;     &quot;paid.y&quot;      
## [41] &quot;activities.y&quot; &quot;higher.y&quot;     &quot;romantic.y&quot;   &quot;famrel.y&quot;     &quot;freetime.y&quot;  
## [46] &quot;goout.y&quot;      &quot;dalc.y&quot;       &quot;walc.y&quot;       &quot;health.y&quot;     &quot;absences.y&quot;  
## [51] &quot;g1.y&quot;         &quot;g2.y&quot;         &quot;g3.y&quot;
</code></pre>
<p>The data set measures the grades for each students achievements at three time intervals, g1, g2 and g3. So grades at g1 and g2 can been used to predict g3, and from the paper, it can be seen that there is a strong correlation between g3 and g2/g1.</p>
<h2 id="population-vs-sample">Population vs Sample</h2>
<p>We are interested in finding results for the entire population of students that have completed exams in maths and Portuguese in Portugal, but we know that is not possible, so what we have is a sample. We will use this sample to infer things about the population as a whole.</p>
<p>The numbers used to describe a population are called parameters, whereas for our sample which is a subset of the pollution, we call them statistics.</p>
<p>Samples are collected because there are easier to contact, less time consuming and less costly.</p>
<p>However taking samples as shortcut to finding out answers about a population is always prone to sampling error.</p>
<p>We now need to ask ourselves some questions.</p>
<ul>
<li>Does our sample represent the population well?</li>
<li>Is our sample biased?</li>
</ul>
<p>In order to answer these questions, we need to explore the data. The first thing we know is that the size of the data set is 382. Usually the bigger the sample the more likely it is to reflect the whole population. It is not enough to simply use the number of records to tell us whether we have a sample that represents the population.</p>
<p>We need to have some understanding of the population in order to make this decision about our sample representing the population. First thing we know is that this data comes from two Portuguese schools, so if we find some statistics from this data set, we can’t say that this applies to students all over the world. We can only use this results as a pointer to further research.</p>
<p>We ask ourselves this question, because in the end we want to be able to create a model that describes the population, not a model which only describes the sample.</p>
<p>We will show later that there are many statistical tests we can do on a sample set of data to see if we can infer anything about the population. Also we will show that through the use of hypotheses testing we can decide whether there is a relationship in the sample data that is strong enough to use to model the relationship in the population.</p>
<p>Now to the 2nd question, a biased sample is one which differs from the population from which it is taken. This can happen if the sample is not collected randomly. If the students in this sample were picked, then it would not be a representative sample.
There is a limit to this randomness, we have to acknowledge that, looking at the paper(Cortez and Silva <a href="#ref-cortez2008using">2008</a>), we see that data was only collected during one year and only in two public schools. This year and these schools might not represent the population’s Portugese school system in other parts of the country and in other years. Doing a quick Google search I can see that these schools are in rural and less dense areas of Portugal.</p>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3194283.005649975!2d-10.17086483750003!3d38.57024409999999!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0xd19e50ed36b8271%3A0xa2f44287b70a82c0!2sEscola%20Gabriel%20pereira!5e0!3m2!1sen!2sie!4v1604499877562!5m2!1sen!2sie" width="300" height="450" frameborder="0" style="border:0;" allowfullscreen aria-hidden="false" tabindex="0">
</iframe>
<iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d4445653.247860987!2d-10.805082784867597!3d39.909816886764695!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x0%3A0x39781f2296c8dbc3!2sMouzinho%20da%20Silveira%20High%20School!5e0!3m2!1sen!2sie!4v1604501863240!5m2!1sen!2sie" width="300" height="450" frameborder="0" style="border:0;" allowfullscreen aria-hidden="true" tabindex="0">
</iframe>
<div class="figure">
<p><img src="https://upload.wikimedia.org/wikipedia/commons/b/b1/Densidade_populacional_por_concelho_-_INE_2001.png" alt="Population density of Portugal @wikiportmap" width="50%" /></p>
<p class="caption">
<p>Figure 1: Population density of Portugal (“Wikipedia” <a href="#ref-wikiportmap">2020</a>)</p>
</p>
</div>
<p>We can also check the if the sample percentages match what we would imagine for a population, for example:
Let checks the students involved, are both sexes represented<br>
counts:</p>
<pre><code>## sex
##   F   M 
## 198 184
</code></pre>
<p>Percentages</p>
<pre><code>## sex
##     F     M 
## 51.83 48.17
</code></pre>
<p>It is very important that when choosing a sample that any missing data is also random, that there is not pattern between the variables which are missing.</p>
<p>To make good decisions to the questions outlined above, we will calculate some simple statistics for our sample. These statistics we will start to examine in the next section.</p>
<h2 id="how-to-infer-from-a-sample-to-a-population">How to infer from a sample to a population</h2>
<p>In order to show how well a sample is representing a population we need to understand some basics about the variables in our data set.
Each variable falls into a “level of Measurement” category. There are 4 levels:</p>
<ul>
<li>Nominal - or Categorical, can we binary variables such as dead or alive or nominal like Guinness, Harp, Smithwicks.</li>
<li>Ordinal - kinda of the same as nominal but have an order, like A,B,C for an exam result.</li>
<li>Interval - have a score and the differences between these scores are equivalent.</li>
<li>Ratio - same as interval but the score of say 12 must mean twice a score of 6. 0 has a meaning.</li>
</ul>
<p>So depending on the variable of interest in the record, we can make small basic models to see if we can infer information about the population from it. The first is mean. First thing we should note is that you can only get a mean from variable which are either interval or Ratio (these types are referred to as numeric in <a href="/blog/description/">here</a>). The other types types such as Nominal and Ordinal don’t have a mean. They use other statistics to describe what we call a Central Tendency. Here is a table to explain:</p>
<table>
<thead>
<tr>
<th>level</th>
<th>Mode</th>
<th>Median</th>
<th>Mean</th>
</tr>
</thead>
<tbody>
<tr>
<td>Nominal</td>
<td>yes</td>
<td>no</td>
<td>no</td>
</tr>
<tr>
<td>Ordinal</td>
<td>yes</td>
<td>yes</td>
<td>no</td>
</tr>
<tr>
<td>Interval</td>
<td>yes</td>
<td>yes</td>
<td>yes</td>
</tr>
<tr>
<td>Ratio</td>
<td>yes</td>
<td>yes</td>
<td>yes</td>
</tr>
</tbody>
</table>
<p>The best measure of Central Tendency is Mean if it is available for that level. If not, then median and if not median then mode. However whether to choose mean or median depends on another term called “skew”. If a variable has skew then median may be better than mode.</p>
<p>To explain these levels, we will use examples in our data set. An example of a Nominal variable, a Numeric variable and a Ratio variable.</p>
<p>Ratio in the student data set is “g3”</p>
<pre><code>32 G3 - final grade (numeric: from 0 to 20, output target)
</code></pre>
<p>Nominal in student data set is “reason”</p>
<pre><code>11 reason - reason to choose this school (nominal: close to &quot;home&quot;, school &quot;reputation&quot;, &quot;course&quot; preference or &quot;other&quot;)
</code></pre>
<p>Ordinal in student data set is “studytime”</p>
<pre><code>14 studytime - weekly study time (numeric: 1 - &lt;2 hours, 2 - 2 to 5 hours, 3 - 5 to 10 hours, or 4 - &gt;10 hours)
</code></pre>
<h2 id="g3---final-grade-ratio">G3 - Final Grade (Ratio)</h2>
<p>In this section we will explore the variable G3 in our data set. The Grade G3 variable is a ratio variable because zero has a meaning in this variable. The grade results begins at zero and a student who got 16 did twice as well as a student who received 8.</p>
<h3 id="normal-distrubution">Normal Distrubution</h3>
<p>We would like to find a variable which has a normal distribution, because we can use parametric tests on this variable. This is ideal when we want to make inference from our sample to our population. These parametric tests are more powerful because they use all values a variable has. Let’s check if grade results fits the bill for us.</p>
<p>Finally we get to draw a chart. First the humble scatter plot:</p>
<div class="figure">
<p><img src="/blog/posts/studentperf/index_files/figure-html/unnamed-chunk-7-1.png" alt="G3 - final grade unsorted" width="672" /></p>
<p class="caption">
<p>Figure 2: G3 - final grade unsorted</p>
</p>
</div>
<p>Or if we sort the grades in ascending order.</p>
<div class="figure">
<p><img src="/blog/posts/studentperf/index_files/figure-html/unnamed-chunk-8-1.png" alt="G3 - final grade sorted" width="672" /></p>
<p class="caption">
<p>Figure 3: G3 - final grade sorted</p>
</p>
</div>
<p>We can see here that there are grade marked as 0. We don’t know if that means the student didn’t do the exam or they got 0 after attempting it. That’s 10.21 % of the data.</p>
<p>To understand skew we need to starting visualizing the data. We do this by plotting what is known as a frequency distribution or histogram.</p>
<div class="figure">
<p><img src="/blog/posts/studentperf/index_files/figure-html/unnamed-chunk-9-1.png" alt="G3 - final grade histogram" width="672" /></p>
<p class="caption">
<p>Figure 4: G3 - final grade histogram</p>
</p>
</div>
<p>From the Frequency distribution chart we can say that the zeros are outliers here, as we said above. WHy? because we expect the distribution for grade results to be normal, to match what we call a <a href="https://www.mathsisfun.com/data/standard-normal-distribution.html">Normal Distrbtion</a>. All normal distributions are symmetric and have bell-shaped density curves with a single peak. This histogram above is bimodal because of the zeros. We will remove those now, for all grade results.</p>
<p>These zeros which we find the grade results could also be a result of missing data.
and now again we check the histogram</p>
<div class="figure">
<p><img src="/blog/posts/studentperf/index_files/figure-html/unnamed-chunk-11-1.png" alt="G3 - final grade histogram no zeros" width="672" /></p>
<p class="caption">
<p>Figure 5: G3 - final grade histogram no zeros</p>
</p>
</div>
<p>This is much better. Let’s check the Central Tendency measure for this variable</p>
<h3 id="central-tendency">Central Tendency</h3>
<p>For G3 - final grade in maths</p>
<table>
<thead>
<tr>
<th>stat</th>
<th>desc</th>
<th>value</th>
</tr>
</thead>
<tbody>
<tr>
<td>mean</td>
<td>average</td>
<td>11.5685131</td>
</tr>
<tr>
<td>median</td>
<td>ranked in order of magnitude, find middle</td>
<td>11</td>
</tr>
</tbody>
</table>
<h3 id="dispersion">Dispersion</h3>
<p>For G3 - final grade in maths</p>
<table>
<thead>
<tr>
<th>stat</th>
<th>desc</th>
<th>value</th>
</tr>
</thead>
<tbody>
<tr>
<td>Range</td>
<td>lowest and highest</td>
<td>4, 20</td>
</tr>
<tr>
<td>Quantiles</td>
<td>cut in 1/4ths</td>
<td>4, 9, 11, 14, 20</td>
</tr>
<tr>
<td>1st quantile</td>
<td>1st 1/4</td>
<td>4</td>
</tr>
<tr>
<td>Interquartile Range</td>
<td>cut off the 1st 1/4 and last 1/4</td>
<td>5</td>
</tr>
<tr>
<td>Variance</td>
<td>The average of the squared differences from the Mean</td>
<td>10.772339</td>
</tr>
<tr>
<td>Standard deviation</td>
<td>the square root of the variance</td>
<td>3.2821242</td>
</tr>
</tbody>
</table>
<p>There are two main ways in which a distribution can deviate from normal:</p>
<ol>
<li>lack of symmetry (called <strong>skew</strong> ) and</li>
<li>pointyness (called <strong>kurtosis</strong> )</li>
</ol>
<p>Like plot the histogram again and add a normal distribution curve using the grade scores:</p>
<pre><code>## Warning: Removed 39 rows containing non-finite values (stat_bin).
</code></pre>
<div class="figure">
<p><img src="/blog/posts/studentperf/index_files/figure-html/unnamed-chunk-12-1.png" alt="G3 - final grade histogram with normal curve" width="672" /></p>
<p class="caption">
<p>Figure 6: G3 - final grade histogram with normal curve</p>
</p>
</div>
<p>From a look at this histogram we can say that the Skew is visible. We can see that there is positive skew.
The kurtosis does not look to be a problem.</p>
<p>We not need to examine that skew in detail. There is another useful graph that we can inspect to see if a distribution is normal called a
Q-Q plot (quantile–quantile plot). A quantile is the proportion of cases we find below a certain value.</p>
<div class="figure">
<p><img src="/blog/posts/studentperf/index_files/figure-html/unnamed-chunk-13-1.png" alt="G3 - final grade Q-Q plot" width="672" /></p>
<p class="caption">
<p>Figure 7: G3 - final grade Q-Q plot</p>
</p>
</div>
<p>The closer the values fall on the diagonal of the plot, the closer the fit we have for a normal distribution.</p>
<p>We can get values now for Skew and kurtosis. The values of skew and kurtosis should be zero
in a normal distribution. Positive values of skew indicate a postive skew. Positive values of
kurtosis indicate a pointy distribution, whereas negative values indicate a flat distribution.</p>
<p>Generating some summary statistics of the varaible. There are two libraries in R for this:
using psych::describe :</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">knitr<span style="color:#f92672">::</span><span style="color:#a6e22e">kable</span>(<span style="color:#a6e22e">stack</span>(psych<span style="color:#f92672">::</span><span style="color:#a6e22e">describe</span>(studentdf<span style="color:#f92672">$</span>g3.x)))
</code></pre></div><table>
<thead>
<tr>
<th style="text-align:right">values</th>
<th style="text-align:left">ind</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right">1.0000000</td>
<td style="text-align:left">vars</td>
</tr>
<tr>
<td style="text-align:right">343.0000000</td>
<td style="text-align:left">n</td>
</tr>
<tr>
<td style="text-align:right">11.5685131</td>
<td style="text-align:left">mean</td>
</tr>
<tr>
<td style="text-align:right">3.2821242</td>
<td style="text-align:left">sd</td>
</tr>
<tr>
<td style="text-align:right">11.0000000</td>
<td style="text-align:left">median</td>
</tr>
<tr>
<td style="text-align:right">11.5018182</td>
<td style="text-align:left">trimmed</td>
</tr>
<tr>
<td style="text-align:right">2.9652000</td>
<td style="text-align:left">mad</td>
</tr>
<tr>
<td style="text-align:right">4.0000000</td>
<td style="text-align:left">min</td>
</tr>
<tr>
<td style="text-align:right">20.0000000</td>
<td style="text-align:left">max</td>
</tr>
<tr>
<td style="text-align:right">16.0000000</td>
<td style="text-align:left">range</td>
</tr>
<tr>
<td style="text-align:right">0.2096557</td>
<td style="text-align:left">skew</td>
</tr>
<tr>
<td style="text-align:right">-0.4840774</td>
<td style="text-align:left">kurtosis</td>
</tr>
<tr>
<td style="text-align:right">0.1772180</td>
<td style="text-align:left">se</td>
</tr>
</tbody>
</table>
<p>using pastecs::stat.desc :</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">options</span>(scipen<span style="color:#f92672">=</span><span style="color:#ae81ff">999</span>)
knitr<span style="color:#f92672">::</span><span style="color:#a6e22e">kable</span>(pastecs<span style="color:#f92672">::</span><span style="color:#a6e22e">stat.desc</span>(studentdf<span style="color:#f92672">$</span>g3.x, basic <span style="color:#f92672">=</span> <span style="color:#66d9ef">FALSE</span>, norm <span style="color:#f92672">=</span> <span style="color:#66d9ef">TRUE</span>))
</code></pre></div><table>
<thead>
<tr>
<th style="text-align:left"></th>
<th style="text-align:right">x</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left">median</td>
<td style="text-align:right">11.0000000</td>
</tr>
<tr>
<td style="text-align:left">mean</td>
<td style="text-align:right">11.5685131</td>
</tr>
<tr>
<td style="text-align:left">SE.mean</td>
<td style="text-align:right">0.1772180</td>
</tr>
<tr>
<td style="text-align:left">CI.mean.0.95</td>
<td style="text-align:right">0.3485745</td>
</tr>
<tr>
<td style="text-align:left">var</td>
<td style="text-align:right">10.7723390</td>
</tr>
<tr>
<td style="text-align:left">std.dev</td>
<td style="text-align:right">3.2821242</td>
</tr>
<tr>
<td style="text-align:left">coef.var</td>
<td style="text-align:right">0.2837118</td>
</tr>
<tr>
<td style="text-align:left">skewness</td>
<td style="text-align:right">0.2096557</td>
</tr>
<tr>
<td style="text-align:left">skew.2SE</td>
<td style="text-align:right">0.7960411</td>
</tr>
<tr>
<td style="text-align:left">kurtosis</td>
<td style="text-align:right">-0.4840774</td>
</tr>
<tr>
<td style="text-align:left">kurt.2SE</td>
<td style="text-align:right">-0.9216168</td>
</tr>
<tr>
<td style="text-align:left">normtest.W</td>
<td style="text-align:right">0.9787651</td>
</tr>
<tr>
<td style="text-align:left">normtest.p</td>
<td style="text-align:right">0.0000598</td>
</tr>
</tbody>
</table>
<p>We divide the skew statistic by the standard error to get the standardised core for skew and kurtosis
using semTools::skew :</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">tpskew<span style="color:#f92672">&lt;-</span>semTools<span style="color:#f92672">::</span><span style="color:#a6e22e">skew</span>(studentdf<span style="color:#f92672">$</span>g3.x)
tpskew
</code></pre></div><pre><code>## skew (g1)        se         z         p 
## 0.2115020 0.1322600 1.5991380 0.1097899
</code></pre>
<p>and semTools::kurtosis :</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">tpkurt<span style="color:#f92672">&lt;-</span>semTools<span style="color:#f92672">::</span><span style="color:#a6e22e">kurtosis</span>(studentdf<span style="color:#f92672">$</span>g3.x)
tpkurt
</code></pre></div><pre><code>## Excess Kur (g2)              se               z               p 
##     -0.45855837      0.26452003     -1.73354877      0.08299818
</code></pre>
<p>Skew and kurtosis are converted to z-scores by dividing by the standard error:</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">tpskew[1]<span style="color:#f92672">/</span>tpskew[2]
</code></pre></div><pre><code>## skew (g1) 
##  1.599138
</code></pre>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">tpkurt[1]<span style="color:#f92672">/</span>tpkurt[2]
</code></pre></div><pre><code>## Excess Kur (g2) 
##       -1.733549
</code></pre>
<p>Before exploring skew and kurtosis, we need to understand a key term “Confidence interval” and “Z-score”</p>
<h3 id="confidence-interval">Confidence interval</h3>
<p>In statistics we use confidence intervals to show how sure we are that a value would fall in a range of values.</p>
<p>The common confidence intervals used are 90%, 95% and 99%. The idea is based on the Normal distribution. To say we are 95% confidence a value will fall into a range of values is the same as saying it will fall inside -1.96 standard deviations and +1.96 standard deviations of the mean. A 90% chance would correspond to 1.645 and a 99% chance would correspond to 2.576 deviations.</p>
<p>Which confidence interval we decide to use depends on the population variance and also the size of the sample. A wide variance in a population would mean a large confidence interval. Certain industries use different confidence intervals to report their results when they are doing tests to answers questions. These tests usually involves fitting a statistical model to data and testing a prediction. To decide if the model works, they need to know if the result is statistically significant. To do this the confidence intervals are used, if the test result is outside these intervals, or above a certain alpha value (usually 0.05), it unlikely the model is getting the right answer by chance. We will discuss this more later in hypothesis testing.</p>
<h3 id="z-score">Z-score</h3>
<p>We only need the standard deviation and mean to use Confidence Intervals. To help us understand what are the critical values and their related probabilities. We need to standardize our Normal Distribution. To do this, we use z-scores. A standard Normal distribution has a mean of zero and standard deviation of one. The z-score is a number on the horizontal which corresponds to a number of standard deviations. So a z-score of 3 means that we are 3 standard deviations from the mean to the right. A z-score also comes with a z-score table, we can use this to calculate the area under the standard normal distribution, this area will give us a probability (and of course there is tools in R to help so we never really need to check a table, although could be useful with electricity goes out). If our distribution is normal for a give variable, then these z-score make it real easy to see for each value the probability of getting that value and the distance the value is from the mean.</p>
<!-- The significance level is an expression of how rare your results are, under the assumption that the null hypothesis is true. It is usually expressed as a “p-value,” and the lower the p-value, the less likely the results are due purely to chance. -->
<p>The critical values for a 95% confidence is -1.96 or +1.96 as we said above, these are the values in terms of z-score or standard deviations. If we get a z-score higher or lower than this, we know that that value is statistically unlikely.</p>
<div class="figure">
<p><img src="normaldistri.png" alt="Standard Normal Distribution" width="100%" /></p>
<p class="caption">
<p>Figure 8: Standard Normal Distribution</p>
</p>
</div>
<p>In the diagram above, you can see how a 95% confidence interval relates to a 19.96 z-score. 2.5% of the area is shaded in in blue, twice that on each side is 5% which is 100% - 5%.</p>
<p>In green you can also see the area which are divided by the -1.96 z-score. These areas are the probabilities or p-values of a event falling into that z-score range.</p>
<h3 id="skew-and-kurtosis-analysis">skew and kurtosis analysis</h3>
<p>We would expect the calculation of skew and kurtosis to be at least less than approx absolute 2 (1.96 for a 95% confidence interval at p &lt; .05). So what we need to do is check the z-score of skew.
Above we calculated a skew of 1.599138. Putting that on our magnificent Standard Normal Distribution figure below. We see it falls in the p &lt; 0.05 range.</p>
<div class="figure">
<p><img src="normaldistri_skew.png" alt="Standard Normal Distribution for skew and kurtosis" width="100%" /></p>
<p class="caption">
<p>Figure 9: Standard Normal Distribution for skew and kurtosis</p>
</p>
</div>
<p>We also calculated a kurtosis of -1.733549.</p>
<p>Sometimes a skew and kurtosis maybe outside our confidence range, however Discovery Statistics with R (<a href="#ref-field2012discovering">2012</a>) estimates that if we have a sample size of 200 or more, it may be more important to look at the shape of the distribution and pay less attention to these scores above.</p>
<p>We say the z-value is significant if it is in those blue regions of the figure above. Significant means important and in the case of skew or kurtosis it’s not good if it is very significant.</p>
<p><em>Another way</em>
Using skew.2SE from pastecs::stat.desc</p>
<p>We can determine if the skew is significant also, skew.2SE is 0.79604109916. This statistic is the skew divided by 2 standard errors. For this to be significant. skew.2SE must be greater than ~1 (or 1.96/2 which is 0.98). It’s not.</p>
<p>Using kurt.2SE from pastecs::stat.desc</p>
<p>kurtosis divided by 2 standard errors we have -0.92161679721. Again kurtosis is just greater than -1 or we could say the absolute value is less than 1.</p>
<p><em>Another way</em></p>
<p>In other to show another way of testing for skew and kurtosis which is called the Shapiro–Wilk test, we need an introduction to Hypothesis testing.</p>
<h3 id="hypothesis-testing">Hypothesis Testing</h3>
<p>We make a hypothesis about the outcome of some experiment. We can make an example from our data set, let’s say students who have more “studytime” achieve better grades (“g3”).</p>
<p>We do the experiment. It’s already done, because we have the data.</p>
<p><strong>H</strong><sub><strong>0</strong></sub>: The <strong>Null hypothesis</strong> would be that “studytime” has no affect on grade results, that “studytime” makes no difference.</p>
<p><strong>H</strong><sub><strong>1</strong></sub>: The <strong>Alternative hypothesis</strong> would be the hypothesis we made above, that students who have more “studytime” achieve better grades.</p>
<p>Afterwards…</p>
<p>For both these hypothesisesesss:</p>
<p>We can either reject the hypothesis(we were wrong) or fail to reject the hypothesis(we are not completely wrong).</p>
<p>We would really like to reject the Null hypothesis.</p>
<p>In order to decide if we reject or fail to reject, we run the data through sometime called a statistical test.</p>
<p>There are two types of errors which can result form a hypothesis test
1. type I: when we reject the Null hypothesis when it is true, probability of committing a type I error is called the significance level, also called alpha. alpha for us is usually 0.05. But it’s depends on the area/industry. False Positive
2. type II: when we fail to reject the Null hypothesis when it is false, probability of committing a type I error is called beta. The probability of not committing type II is called the power. False Negative</p>
<p>I liked Wikipedia’s description of these:
type I: “an innocent person is convicted”
type II: “a guilty person is not convicted”</p>
<div class="figure">
<p><img src="typeI_typeII.png" alt="Type I and Type II Errors" width="100%" /></p>
<p class="caption">
<p>Figure 10: Type I and Type II Errors</p>
</p>
</div>
<p>The strength of the evidence of is determined by the measureed p-value of the test and by the region of acceptance.</p>
<h3 id="shapirowilk-test">Shapiro–Wilk test</h3>
<p>Another way to check if our variable has a normal distribution is do the Shapiro–Wilk test.</p>
<p>This test compares the mean and standard deviation of our data to a normally distributed set of scores withe h same mean and standard deviation.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">shapiro.test</span>(studentdf<span style="color:#f92672">$</span>g3.x)
</code></pre></div><pre><code>## 
##  Shapiro-Wilk normality test
## 
## data:  studentdf$g3.x
## W = 0.97877, p-value = 0.00005978
</code></pre>
<p>The test result shows the test statistic and the p-value.</p>
<p>The Null hypothesis is that there is no normal distribution in this data, it’s just random stuff.
The alternative hypothesis is that it’s a normal distribution.</p>
<p>Our result has a very small p-value, so the probability that the Null hypothesis is true is tiny, so we can accept the Alternative.</p>
<p>A p-value of less than 0.05 is statistically significant here, so if our p-value was greater than 0.05. We could not reject <strong>H</strong><sub><strong>0</strong></sub>.</p>
<p>This test along with the Kolmogorov-Smirnov test are usually not the greatest indicators to a varaible being non-normal.
The best way to test for normality is outlined already in the section <a href="#dispersion">dispersion</a>. When testing again for normality I will refer to this section.</p>
<h3 id="using-normal-distribution-to-find-outliers">Using Normal Distribution to find outliers</h3>
<p>Now by calculating the percentage of standardized scores for the variable itself that are outside our acceptable range
we can see how far they are away from being normal.
Calculate the percentage of standardised scores that are greater than 1.96</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">ztpcoiss<span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">abs</span>(<span style="color:#a6e22e">scale</span>(studentdf<span style="color:#f92672">$</span>g3.x))

FSA<span style="color:#f92672">::</span><span style="color:#a6e22e">perc</span>(<span style="color:#a6e22e">as.numeric</span>(ztpcoiss), <span style="color:#ae81ff">1.96</span>, <span style="color:#e6db74">&#34;gt&#34;</span>)
</code></pre></div><pre><code>## [1] 4.081633
</code></pre>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">FSA<span style="color:#f92672">::</span><span style="color:#a6e22e">perc</span>(<span style="color:#a6e22e">as.numeric</span>(ztpcoiss), <span style="color:#ae81ff">2.58</span>, <span style="color:#e6db74">&#34;gt&#34;</span>)
</code></pre></div><pre><code>## [1] 0
</code></pre>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">FSA<span style="color:#f92672">::</span><span style="color:#a6e22e">perc</span>(<span style="color:#a6e22e">as.numeric</span>(ztpcoiss), <span style="color:#ae81ff">3.29</span>, <span style="color:#e6db74">&#34;gt&#34;</span>)
</code></pre></div><pre><code>## [1] 0
</code></pre>
<p>So 4% of our data lies outside 1.96 standard deviations of the mean or outside the 95% confidence range.
0% are outside of the 99% confidence interval and of course that means also 0% of our data lies outside the 99.9% confidence interval.</p>
<p>95% of our data is within the acceptable range, so we can treat the data as normal. 😌</p>
<p>Since our sample size is larger than 80, a case is an outlier if it’s standard score is +/- 3.29. So we have no outliers. HOwever at the moment we are ignoring missing data, that’s eh values we made NA earlier.</p>
<h3 id="g3-grades-summary">G3 Grades Summary</h3>
<table>
<thead>
<tr>
<th>Heuristic</th>
<th>value</th>
</tr>
</thead>
<tbody>
<tr>
<td>Standarised score of skew</td>
<td>1.599138</td>
</tr>
<tr>
<td>Standarised score of kurtosis</td>
<td>-1.733549</td>
</tr>
<tr>
<td>Standarised score of variables</td>
<td>4.1 % outside +/- 1.96</td>
</tr>
<tr>
<td>Standarised score of variables</td>
<td>0% outside +/- 3.29 (no outliers)</td>
</tr>
<tr>
<td>Currently ignoring missing data.</td>
<td></td>
</tr>
</tbody>
</table>
<h2 id="reason-nominal">Reason (Nominal)</h2>
<p>Reason has the following description in the data set.</p>
<pre><code>11 reason - reason to choose this school (nominal: close to &quot;home&quot;, school &quot;reputation&quot;, &quot;course&quot; preference or &quot;other&quot;)
</code></pre>
<p>As we explained earlier it is nominal because there is no ordering or direction in this variable. In the R language we call this column a factor.</p>
<p>The best way to visualize this variable is to use a pie chart, bar chart or a frequency table.
<img src="/blog/posts/studentperf/index_files/figure-html/unnamed-chunk-26-1.png" width="672" /></p>
<pre><code>##       reason   n
## 1     course 140
## 2       home 110
## 3      other  34
## 4 reputation  98
</code></pre>
<p><img src="/blog/posts/studentperf/index_files/figure-html/unnamed-chunk-26-2.png" width="672" /></p>
<h2 id="studytime-ordinal">Studytime (Ordinal)</h2>
<p>Studytime has the following description in the data set.</p>
<pre><code>14 studytime - weekly study time (numeric: 1 - &lt;2 hours, 2 - 2 to 5 hours, 3 - 5 to 10 hours, or 4 - &gt;10 hours)
</code></pre>
<p>It is ordinal because it has an order, but it is not interval because the different between each value is not the same, also we can’t add or subtract values.</p>
<p>From the join we did earlier with the data from the two subject, we have two columns of studytime. Let’s compare them.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">print</span>(<span style="color:#e6db74">&#34;Length of studytime.x&#34;</span>)
<span style="color:#a6e22e">length</span>(studentdf<span style="color:#f92672">$</span>studytime.x)
a <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">is.na</span>(studentdf<span style="color:#f92672">$</span>studytime.x)
<span style="color:#a6e22e">print</span>(<span style="color:#e6db74">&#34;Number of NA values in studytime.x&#34;</span>)
<span style="color:#a6e22e">length</span>(a[a<span style="color:#f92672">==</span><span style="color:#66d9ef">TRUE</span>])
<span style="color:#a6e22e">print</span>(<span style="color:#e6db74">&#34;Length of studytime.y&#34;</span>)
<span style="color:#a6e22e">length</span>(studentdf<span style="color:#f92672">$</span>studytime.y)
a <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">is.na</span>(studentdf<span style="color:#f92672">$</span>studytime.y)
<span style="color:#a6e22e">print</span>(<span style="color:#e6db74">&#34;Number of NA values in studytime.y&#34;</span>)
<span style="color:#a6e22e">length</span>(a[a<span style="color:#f92672">==</span><span style="color:#66d9ef">TRUE</span>])
<span style="color:#a6e22e">print</span>(<span style="color:#e6db74">&#34;Are they equal? how many of different? &#34;</span>)
a <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">sort</span>(studentdf<span style="color:#f92672">$</span>studytime.x) <span style="color:#f92672">==</span> <span style="color:#a6e22e">sort</span>(studentdf<span style="color:#f92672">$</span>studytime.y)
<span style="color:#a6e22e">length</span>(a[a<span style="color:#f92672">==</span><span style="color:#66d9ef">FALSE</span>])
</code></pre></div><pre><code>## [1] &quot;Length of studytime.x&quot;
## [1] 382
## [1] &quot;Number of NA values in studytime.x&quot;
## [1] 0
## [1] &quot;Length of studytime.y&quot;
## [1] 382
## [1] &quot;Number of NA values in studytime.y&quot;
## [1] 0
## [1] &quot;Are they equal? how many of different? &quot;
## [1] 2
</code></pre>
<p>Ok, so the two sets of data for the two subjects might not be joined perfectly, but we are talking about 2 values in 382, so not going to have a huge impact. I will choose to use studytime.x from now on.</p>
<p>In R, we can add the information from the levels in the description of studytime.x to the variable and we can do this for all similar type variables.
In R these are known as ordinal factors.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">studentdf<span style="color:#f92672">$</span>medu <span style="color:#f92672">=</span> <span style="color:#a6e22e">factor</span>(studentdf<span style="color:#f92672">$</span>medu,levels<span style="color:#f92672">=</span><span style="color:#a6e22e">c</span>(<span style="color:#ae81ff">0</span><span style="color:#f92672">:</span><span style="color:#ae81ff">4</span>),labels <span style="color:#f92672">=</span> <span style="color:#a6e22e">c</span>(<span style="color:#e6db74">&#34;0 - none&#34;</span>,<span style="color:#e6db74">&#34;1 - primary education (4th grade)&#34;</span>,<span style="color:#e6db74">&#34;2 – 5th to 9th grade&#34;</span>,<span style="color:#e6db74">&#34;3 – secondary education&#34;</span>,<span style="color:#e6db74">&#34;4 – higher education&#34;</span>), ordered<span style="color:#f92672">=</span>T)
studentdf<span style="color:#f92672">$</span>fedu <span style="color:#f92672">=</span> <span style="color:#a6e22e">factor</span>(studentdf<span style="color:#f92672">$</span>fedu,levels<span style="color:#f92672">=</span><span style="color:#a6e22e">c</span>(<span style="color:#ae81ff">0</span><span style="color:#f92672">:</span><span style="color:#ae81ff">4</span>),labels <span style="color:#f92672">=</span> <span style="color:#a6e22e">c</span>(<span style="color:#e6db74">&#34;0 - none&#34;</span>,<span style="color:#e6db74">&#34;1 - primary education (4th grade)&#34;</span>,<span style="color:#e6db74">&#34;2 – 5th to 9th grade&#34;</span>,<span style="color:#e6db74">&#34;3 – secondary education&#34;</span>,<span style="color:#e6db74">&#34;4 – higher education&#34;</span>), ordered<span style="color:#f92672">=</span>T)
studentdf<span style="color:#f92672">$</span>traveltime.x <span style="color:#f92672">=</span> <span style="color:#a6e22e">factor</span>(studentdf<span style="color:#f92672">$</span>traveltime.x,levels<span style="color:#f92672">=</span><span style="color:#a6e22e">c</span>(<span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#ae81ff">4</span>),labels <span style="color:#f92672">=</span> <span style="color:#a6e22e">c</span>(<span style="color:#e6db74">&#34;1 - &lt;15 min&#34;</span>, <span style="color:#e6db74">&#34;2 - 15 to 30 min&#34;</span>, <span style="color:#e6db74">&#34;3 - 30 min. to 1 hour&#34;</span>, <span style="color:#e6db74">&#34;4 - &gt;1 hour&#34;</span>), ordered<span style="color:#f92672">=</span>T)
studentdf<span style="color:#f92672">$</span>traveltime.y <span style="color:#f92672">=</span> <span style="color:#a6e22e">factor</span>(studentdf<span style="color:#f92672">$</span>traveltime.y,levels<span style="color:#f92672">=</span><span style="color:#a6e22e">c</span>(<span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#ae81ff">4</span>),labels <span style="color:#f92672">=</span> <span style="color:#a6e22e">c</span>(<span style="color:#e6db74">&#34;1 - &lt;15 min&#34;</span>, <span style="color:#e6db74">&#34;2 - 15 to 30 min&#34;</span>, <span style="color:#e6db74">&#34;3 - 30 min. to 1 hour&#34;</span>, <span style="color:#e6db74">&#34;4 - &gt;1 hour&#34;</span>), ordered<span style="color:#f92672">=</span>T)
studentdf<span style="color:#f92672">$</span>studytime.x <span style="color:#f92672">=</span> <span style="color:#a6e22e">factor</span>(studentdf<span style="color:#f92672">$</span>studytime.x,levels<span style="color:#f92672">=</span><span style="color:#a6e22e">c</span>(<span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#ae81ff">4</span>),labels <span style="color:#f92672">=</span> <span style="color:#a6e22e">c</span>(<span style="color:#e6db74">&#34;1 - &lt;2 hours&#34;</span>,<span style="color:#e6db74">&#34;2 - 2 to 5 hours&#34;</span>, <span style="color:#e6db74">&#34;3 - 5 to 10 hours&#34;</span>,<span style="color:#e6db74">&#34;4 - &gt;10 hours&#34;</span>), ordered<span style="color:#f92672">=</span>T)
studentdf<span style="color:#f92672">$</span>studytime.y <span style="color:#f92672">=</span> <span style="color:#a6e22e">factor</span>(studentdf<span style="color:#f92672">$</span>studytime.y,levels<span style="color:#f92672">=</span><span style="color:#a6e22e">c</span>(<span style="color:#ae81ff">1</span><span style="color:#f92672">:</span><span style="color:#ae81ff">4</span>),labels <span style="color:#f92672">=</span> <span style="color:#a6e22e">c</span>(<span style="color:#e6db74">&#34;1 - &lt;2 hours&#34;</span>,<span style="color:#e6db74">&#34;2 - 2 to 5 hours&#34;</span>, <span style="color:#e6db74">&#34;3 - 5 to 10 hours&#34;</span>,<span style="color:#e6db74">&#34;4 - &gt;10 hours&#34;</span>), ordered<span style="color:#f92672">=</span>T)
</code></pre></div><p><img src="/blog/posts/studentperf/index_files/figure-html/unnamed-chunk-29-1.png" width="960" /></p>
<h2 id="missing-data">Missing Data</h2>
<p>Missing data can come as a result of sampling bias or selection bias. Missing data reduces the probability that the test will reject
<strong>H</strong><sub><strong>0</strong></sub>.</p>
<p>We can take a quick look at our data set and see if we have many NA values.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">t <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">sapply</span>(studentdf, <span style="color:#a6e22e">function</span>(x) <span style="color:#a6e22e">sum</span>(<span style="color:#a6e22e">is.na</span>(x)))
t[t<span style="color:#f92672">&gt;</span><span style="color:#ae81ff">0</span>]
</code></pre></div><pre><code>## g2.x g3.x 
##   13   39
</code></pre>
<p>It is no surprise here at there is not many NAs. Looking back to [Get started] we merged the Maths and Portuguese results together using the variables “school”,“sex”,“age”,“address”,“famsize”,“Pstatus”,“Medu”,“Fedu”,“Mjob”,“Fjob”,“reason”,“nursery”,“internet”</p>
<p>Which means if any of these are missing, we won’t have them in our combined data frame. That means alot of the Portuguese grade data is not contained in the merged data frame.</p>
<p>Missing data reduces also how well sample represents the population, if we had a lot of missing data, it could also lead to invalid conclusions.</p>
<p>There are three possible patterns to missing data:</p>
<ol>
<li>Data missing at random (MAR) - missing data is not random, but not related to other variables</li>
<li>Data missing completely at random (MCAR) - missing data is random, best scenario!</li>
<li>Data not missing at random (MNAR) - not random, related to other variables, pretty serious!</li>
</ol>
<p>Let us check if any of these patterns are seen in the data. The only variables with missing data are the grade results: g2 and g3 for Maths.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">library</span>(<span style="color:#e6db74">&#34;dplyr&#34;</span>)
studentdf <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">filter</span>(<span style="color:#a6e22e">is.na</span>(g3.x)) <span style="color:#f92672">%&gt;%</span> <span style="color:#a6e22e">summary</span>()
</code></pre></div><pre><code>##  school  sex         age        address famsize  pstatus
##  GP:34   F:23   Min.   :15.00   R: 9    GT3:34   A: 2   
##  MS: 5   M:16   1st Qu.:16.00   U:30    LE3: 5   T:37   
##                 Median :17.00                           
##                 Mean   :17.05                           
##                 3rd Qu.:18.00                           
##                 Max.   :19.00                           
##                                                         
##                                 medu                                   fedu   
##  0 - none                         : 0   0 - none                         : 0  
##  1 - primary education (4th grade): 8   1 - primary education (4th grade):13  
##  2 – 5th to 9th grade             :14   2 – 5th to 9th grade             :10  
##  3 – secondary education          : 9   3 – secondary education          : 6  
##  4 – higher education             : 8   4 – higher education             :10  
##                                                                               
##                                                                               
##        mjob          fjob           reason   nursery  internet  guardian.x
##  at_home : 9   at_home : 3   course    :20   no : 9   no : 7   father: 9  
##  health  : 2   health  : 0   home      :13   yes:30   yes:32   mother:26  
##  other   :15   other   :21   other     : 1                     other : 4  
##  services: 7   services:11   reputation: 5                                
##  teacher : 6   teacher : 4                                                
##                                                                           
##                                                                           
##                 traveltime.x            studytime.x   failures.x    
##  1 - &lt;15 min          :22    1 - &lt;2 hours     :13   Min.   :0.0000  
##  2 - 15 to 30 min     :12    2 - 2 to 5 hours :17   1st Qu.:0.0000  
##  3 - 30 min. to 1 hour: 4    3 - 5 to 10 hours: 6   Median :1.0000  
##  4 - &gt;1 hour          : 1    4 - &gt;10 hours    : 3   Mean   :0.9231  
##                                                     3rd Qu.:1.5000  
##                                                     Max.   :3.0000  
##                                                                     
##  schoolsup.x famsup.x paid.x   activities.x higher.x romantic.x    famrel.x    
##  no :38      no :14   no :31   no :19       no : 7   no :19     Min.   :1.000  
##  yes: 1      yes:25   yes: 8   yes:20       yes:32   yes:20     1st Qu.:3.000  
##                                                                 Median :4.000  
##                                                                 Mean   :3.795  
##                                                                 3rd Qu.:5.000  
##                                                                 Max.   :5.000  
##                                                                                
##    freetime.x       goout.x          dalc.x          walc.x     
##  Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000  
##  1st Qu.:3.000   1st Qu.:2.000   1st Qu.:1.000   1st Qu.:1.000  
##  Median :3.000   Median :3.000   Median :1.000   Median :1.000  
##  Mean   :3.103   Mean   :3.128   Mean   :1.333   Mean   :1.821  
##  3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:2.000   3rd Qu.:2.000  
##  Max.   :5.000   Max.   :5.000   Max.   :3.000   Max.   :5.000  
##                                                                 
##     health.x       absences.x      g1.x             g2.x             g3.x    
##  Min.   :1.000   Min.   :0    Min.   : 4.000   Min.   : 5.000   Min.   : NA  
##  1st Qu.:2.500   1st Qu.:0    1st Qu.: 6.000   1st Qu.: 5.250   1st Qu.: NA  
##  Median :4.000   Median :0    Median : 7.000   Median : 7.000   Median : NA  
##  Mean   :3.641   Mean   :0    Mean   : 7.462   Mean   : 7.115   Mean   :NaN  
##  3rd Qu.:5.000   3rd Qu.:0    3rd Qu.: 9.000   3rd Qu.: 8.750   3rd Qu.: NA  
##  Max.   :5.000   Max.   :0    Max.   :12.000   Max.   :10.000   Max.   : NA  
##                                                NA's   :13       NA's   :39   
##   guardian.y                traveltime.y            studytime.y
##  father: 9   1 - &lt;15 min          :20    1 - &lt;2 hours     :13  
##  mother:26   2 - 15 to 30 min     :13    2 - 2 to 5 hours :17  
##  other : 4   3 - 30 min. to 1 hour: 5    3 - 5 to 10 hours: 6  
##              4 - &gt;1 hour          : 1    4 - &gt;10 hours    : 3  
##                                                                
##                                                                
##                                                                
##    failures.y     schoolsup.y famsup.y paid.y   activities.y higher.y
##  Min.   :0.0000   no :37      no :15   no :38   no :17       no : 7  
##  1st Qu.:0.0000   yes: 2      yes:24   yes: 1   yes:22       yes:32  
##  Median :0.0000                                                      
##  Mean   :0.3333                                                      
##  3rd Qu.:0.0000                                                      
##  Max.   :3.0000                                                      
##                                                                      
##  romantic.y    famrel.y       freetime.y       goout.y          dalc.y     
##  no :19     Min.   :1.000   Min.   :1.000   Min.   :1.000   Min.   :1.000  
##  yes:20     1st Qu.:3.000   1st Qu.:3.000   1st Qu.:2.000   1st Qu.:1.000  
##             Median :4.000   Median :3.000   Median :3.000   Median :1.000  
##             Mean   :3.846   Mean   :3.205   Mean   :3.179   Mean   :1.308  
##             3rd Qu.:5.000   3rd Qu.:4.000   3rd Qu.:4.000   3rd Qu.:2.000  
##             Max.   :5.000   Max.   :5.000   Max.   :5.000   Max.   :3.000  
##                                                                            
##      walc.y         health.y       absences.y          g1.y      
##  Min.   :1.000   Min.   :1.000   Min.   : 0.000   Min.   : 5.00  
##  1st Qu.:1.000   1st Qu.:3.000   1st Qu.: 0.000   1st Qu.: 9.00  
##  Median :2.000   Median :4.000   Median : 4.000   Median :11.00  
##  Mean   :1.897   Mean   :3.615   Mean   : 5.179   Mean   :10.62  
##  3rd Qu.:2.000   3rd Qu.:5.000   3rd Qu.: 6.500   3rd Qu.:12.00  
##  Max.   :5.000   Max.   :5.000   Max.   :22.000   Max.   :16.00  
##                                                                  
##       g2.y            g3.y      
##  Min.   : 7.00   Min.   : 0.00  
##  1st Qu.: 9.00   1st Qu.:10.00  
##  Median :11.00   Median :11.00  
##  Mean   :10.67   Mean   :10.85  
##  3rd Qu.:12.00   3rd Qu.:13.00  
##  Max.   :14.00   Max.   :15.00  
## 
</code></pre>
<p>Because our data set is relatively large, we don’t expect missing data to have a serious impact. It all goes back to being representative of the population.</p>
<p>In R we have a library called finalfit which has the function ff_glimpse, whihc we can use to identify missing data.</p>
<pre><code>## $Continuous
##                 label var_type   n missing_n missing_percent mean  sd  min
## age               age    &lt;int&gt; 382         0             0.0 16.6 1.2 15.0
## failures.x failures.x    &lt;int&gt; 382         0             0.0  0.3 0.7  0.0
## famrel.x     famrel.x    &lt;int&gt; 382         0             0.0  3.9 0.9  1.0
## freetime.x freetime.x    &lt;int&gt; 382         0             0.0  3.2 1.0  1.0
## goout.x       goout.x    &lt;int&gt; 382         0             0.0  3.1 1.1  1.0
## dalc.x         dalc.x    &lt;int&gt; 382         0             0.0  1.5 0.9  1.0
## walc.x         walc.x    &lt;int&gt; 382         0             0.0  2.3 1.3  1.0
## health.x     health.x    &lt;int&gt; 382         0             0.0  3.6 1.4  1.0
## absences.x absences.x    &lt;int&gt; 382         0             0.0  5.3 7.6  0.0
## g1.x             g1.x    &lt;int&gt; 382         0             0.0 10.9 3.3  3.0
## g2.x             g2.x    &lt;int&gt; 369        13             3.4 11.1 3.3  5.0
## g3.x             g3.x    &lt;int&gt; 343        39            10.2 11.6 3.3  4.0
## failures.y failures.y    &lt;int&gt; 382         0             0.0  0.1 0.5  0.0
## famrel.y     famrel.y    &lt;int&gt; 382         0             0.0  3.9 0.9  1.0
## freetime.y freetime.y    &lt;int&gt; 382         0             0.0  3.2 1.0  1.0
## goout.y       goout.y    &lt;int&gt; 382         0             0.0  3.1 1.1  1.0
## dalc.y         dalc.y    &lt;int&gt; 382         0             0.0  1.5 0.9  1.0
## walc.y         walc.y    &lt;int&gt; 382         0             0.0  2.3 1.3  1.0
## health.y     health.y    &lt;int&gt; 382         0             0.0  3.6 1.4  1.0
## absences.y absences.y    &lt;int&gt; 382         0             0.0  3.7 4.9  0.0
## g1.y             g1.y    &lt;int&gt; 382         0             0.0 12.1 2.6  0.0
## g2.y             g2.y    &lt;int&gt; 382         0             0.0 12.2 2.5  5.0
## g3.y             g3.y    &lt;int&gt; 382         0             0.0 12.5 2.9  0.0
##            quartile_25 median quartile_75  max
## age               16.0   17.0        17.0 22.0
## failures.x         0.0    0.0         0.0  3.0
## famrel.x           4.0    4.0         5.0  5.0
## freetime.x         3.0    3.0         4.0  5.0
## goout.x            2.0    3.0         4.0  5.0
## dalc.x             1.0    1.0         2.0  5.0
## walc.x             1.0    2.0         3.0  5.0
## health.x           3.0    4.0         5.0  5.0
## absences.x         0.0    3.0         8.0 75.0
## g1.x               8.0   10.5        13.0 19.0
## g2.x               9.0   11.0        13.0 19.0
## g3.x               9.0   11.0        14.0 20.0
## failures.y         0.0    0.0         0.0  3.0
## famrel.y           4.0    4.0         5.0  5.0
## freetime.y         3.0    3.0         4.0  5.0
## goout.y            2.0    3.0         4.0  5.0
## dalc.y             1.0    1.0         2.0  5.0
## walc.y             1.0    2.0         3.0  5.0
## health.y           3.0    4.0         5.0  5.0
## absences.y         0.0    2.0         6.0 32.0
## g1.y              10.0   12.0        14.0 19.0
## g2.y              11.0   12.0        14.0 19.0
## g3.y              11.0   13.0        14.0 19.0
## 
## $Categorical
##                     label var_type   n missing_n missing_percent levels_n
## school             school    &lt;fct&gt; 382         0             0.0        2
## sex                   sex    &lt;fct&gt; 382         0             0.0        2
## address           address    &lt;fct&gt; 382         0             0.0        2
## famsize           famsize    &lt;fct&gt; 382         0             0.0        2
## pstatus           pstatus    &lt;fct&gt; 382         0             0.0        2
## medu                 medu    &lt;ord&gt; 382         0             0.0        5
## fedu                 fedu    &lt;ord&gt; 382         0             0.0        5
## mjob                 mjob    &lt;fct&gt; 382         0             0.0        5
## fjob                 fjob    &lt;fct&gt; 382         0             0.0        5
## reason             reason    &lt;fct&gt; 382         0             0.0        4
## nursery           nursery    &lt;fct&gt; 382         0             0.0        2
## internet         internet    &lt;fct&gt; 382         0             0.0        2
## guardian.x     guardian.x    &lt;fct&gt; 382         0             0.0        3
## traveltime.x traveltime.x    &lt;ord&gt; 382         0             0.0        4
## studytime.x   studytime.x    &lt;ord&gt; 382         0             0.0        4
## schoolsup.x   schoolsup.x    &lt;fct&gt; 382         0             0.0        2
## famsup.x         famsup.x    &lt;fct&gt; 382         0             0.0        2
## paid.x             paid.x    &lt;fct&gt; 382         0             0.0        2
## activities.x activities.x    &lt;fct&gt; 382         0             0.0        2
## higher.x         higher.x    &lt;fct&gt; 382         0             0.0        2
## romantic.x     romantic.x    &lt;fct&gt; 382         0             0.0        2
## guardian.y     guardian.y    &lt;fct&gt; 382         0             0.0        3
## traveltime.y traveltime.y    &lt;ord&gt; 382         0             0.0        4
## studytime.y   studytime.y    &lt;ord&gt; 382         0             0.0        4
## schoolsup.y   schoolsup.y    &lt;fct&gt; 382         0             0.0        2
## famsup.y         famsup.y    &lt;fct&gt; 382         0             0.0        2
## paid.y             paid.y    &lt;fct&gt; 382         0             0.0        2
## activities.y activities.y    &lt;fct&gt; 382         0             0.0        2
## higher.y         higher.y    &lt;fct&gt; 382         0             0.0        2
## romantic.y     romantic.y    &lt;fct&gt; 382         0             0.0        2
##                                                                                                                                  levels
## school                                                                                                                       &quot;GP&quot;, &quot;MS&quot;
## sex                                                                                                                            &quot;F&quot;, &quot;M&quot;
## address                                                                                                                        &quot;R&quot;, &quot;U&quot;
## famsize                                                                                                                    &quot;GT3&quot;, &quot;LE3&quot;
## pstatus                                                                                                                        &quot;A&quot;, &quot;T&quot;
## medu         &quot;0 - none&quot;, &quot;1 - primary education (4th grade)&quot;, &quot;2 – 5th to 9th grade&quot;, &quot;3 – secondary education&quot;, &quot;4 – higher education&quot;
## fedu         &quot;0 - none&quot;, &quot;1 - primary education (4th grade)&quot;, &quot;2 – 5th to 9th grade&quot;, &quot;3 – secondary education&quot;, &quot;4 – higher education&quot;
## mjob                                                                                &quot;at_home&quot;, &quot;health&quot;, &quot;other&quot;, &quot;services&quot;, &quot;teacher&quot;
## fjob                                                                                &quot;at_home&quot;, &quot;health&quot;, &quot;other&quot;, &quot;services&quot;, &quot;teacher&quot;
## reason                                                                                          &quot;course&quot;, &quot;home&quot;, &quot;other&quot;, &quot;reputation&quot;
## nursery                                                                                                                     &quot;no&quot;, &quot;yes&quot;
## internet                                                                                                                    &quot;no&quot;, &quot;yes&quot;
## guardian.x                                                                                                  &quot;father&quot;, &quot;mother&quot;, &quot;other&quot;
## traveltime.x                                                  &quot;1 - &lt;15 min&quot;, &quot;2 - 15 to 30 min&quot;, &quot;3 - 30 min. to 1 hour&quot;, &quot;4 - &gt;1 hour&quot;
## studytime.x                                                    &quot;1 - &lt;2 hours&quot;, &quot;2 - 2 to 5 hours&quot;, &quot;3 - 5 to 10 hours&quot;, &quot;4 - &gt;10 hours&quot;
## schoolsup.x                                                                                                                 &quot;no&quot;, &quot;yes&quot;
## famsup.x                                                                                                                    &quot;no&quot;, &quot;yes&quot;
## paid.x                                                                                                                      &quot;no&quot;, &quot;yes&quot;
## activities.x                                                                                                                &quot;no&quot;, &quot;yes&quot;
## higher.x                                                                                                                    &quot;no&quot;, &quot;yes&quot;
## romantic.x                                                                                                                  &quot;no&quot;, &quot;yes&quot;
## guardian.y                                                                                                  &quot;father&quot;, &quot;mother&quot;, &quot;other&quot;
## traveltime.y                                                  &quot;1 - &lt;15 min&quot;, &quot;2 - 15 to 30 min&quot;, &quot;3 - 30 min. to 1 hour&quot;, &quot;4 - &gt;1 hour&quot;
## studytime.y                                                    &quot;1 - &lt;2 hours&quot;, &quot;2 - 2 to 5 hours&quot;, &quot;3 - 5 to 10 hours&quot;, &quot;4 - &gt;10 hours&quot;
## schoolsup.y                                                                                                                 &quot;no&quot;, &quot;yes&quot;
## famsup.y                                                                                                                    &quot;no&quot;, &quot;yes&quot;
## paid.y                                                                                                                      &quot;no&quot;, &quot;yes&quot;
## activities.y                                                                                                                &quot;no&quot;, &quot;yes&quot;
## higher.y                                                                                                                    &quot;no&quot;, &quot;yes&quot;
## romantic.y                                                                                                                  &quot;no&quot;, &quot;yes&quot;
##                      levels_count                    levels_percent
## school                    342, 40                            90, 10
## sex                      198, 184                            52, 48
## address                   81, 301                            21, 79
## famsize                  278, 104                            73, 27
## pstatus                   38, 344                         9.9, 90.1
## medu           3, 51, 98, 95, 135  0.79, 13.35, 25.65, 24.87, 35.34
## fedu           2, 77, 105, 99, 99  0.52, 20.16, 27.49, 25.92, 25.92
## mjob          53, 33, 138, 96, 62      13.9,  8.6, 36.1, 25.1, 16.2
## fjob         16, 17, 211, 107, 31       4.2,  4.5, 55.2, 28.0,  8.1
## reason           140, 110, 34, 98            36.6, 28.8,  8.9, 25.7
## nursery                   72, 310                            19, 81
## internet                  58, 324                            15, 85
## guardian.x            91, 275, 16                  23.8, 72.0,  4.2
## traveltime.x      250, 103, 21, 8            65.4, 27.0,  5.5,  2.1
## studytime.x      103, 190, 62, 27            27.0, 49.7, 16.2,  7.1
## schoolsup.x               331, 51                            87, 13
## famsup.x                 144, 238                            38, 62
## paid.x                   205, 177                            54, 46
## activities.x             181, 201                            47, 53
## higher.x                  18, 364                         4.7, 95.3
## romantic.x               261, 121                            68, 32
## guardian.y            91, 275, 16                  23.8, 72.0,  4.2
## traveltime.y      250, 102, 22, 8            65.4, 26.7,  5.8,  2.1
## studytime.y      102, 190, 63, 27            26.7, 49.7, 16.5,  7.1
## schoolsup.y               332, 50                            87, 13
## famsup.y                 143, 239                            37, 63
## paid.y                    356, 26                        93.2,  6.8
## activities.y             182, 200                            48, 52
## higher.y                  18, 364                         4.7, 95.3
## romantic.y               259, 123                            68, 32
</code></pre>
<p>I am going to ignore missing data, which is one of the thing we can do with missing data.</p>
<h1 id="relationships">Relationships</h1>
<p>In this section I will explore the relationships between different variables in our data set. The first relationship I would like to explore is Correlation.</p>
<p>I have read many times that in order to look at relationships in a data set probably we must first ask the questions, it is very bad practice to look and the data and try to work backwards to determine relationships. We must set our alpha level also before beginning.</p>
<p>The questions I have for this section are:</p>
<ol>
<li>Is there a linear correlation between the number of school absences and the G3 result.</li>
<li>Is there a linear correlation between the reason to choose this school and the G3 result.</li>
</ol>
<h2 id="correlation-absences-and-g3">Correlation (absences and G3)</h2>
<p>Again we will use hypothesis testing to determine if there is a correlation between the number of school absences and the G3 result.
To make a correlation, we use tests which give us a correlation coefficient, r. This coefficient tells us the strength and the direction of the linear relationship between the number of school absences and the G3 result.</p>
<p>Once we get this correlation coefficient, r, we need to then check if it is statistically significant and whether it can be used to apply to the population.</p>
<p>We start as always with stating the Null and alternative hypothesis:</p>
<p><strong>H</strong><sub><strong>0</strong></sub>: There is NOT a significant linear relationship between the number of school absences and the G3 result.</p>
<p><strong>H</strong><sub><strong>a</strong></sub>: There IS a significant linear relationship between the number of school absences and the G3 result.</p>
<p>We have already studied G3 in the previous section for normality. Let’s study number of school absences now.</p>
<div class="highlight"><pre style="color:#f8f8f2;background-color:#272822;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#a6e22e">print</span>(<span style="color:#e6db74">&#34;Length of absences.x&#34;</span>)
<span style="color:#a6e22e">length</span>(studentdf<span style="color:#f92672">$</span>absences.x)
a <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">is.na</span>(studentdf<span style="color:#f92672">$</span>absences.x)
<span style="color:#a6e22e">print</span>(<span style="color:#e6db74">&#34;Number of NA values in absences.x&#34;</span>)
<span style="color:#a6e22e">length</span>(a[a<span style="color:#f92672">==</span><span style="color:#66d9ef">TRUE</span>])
<span style="color:#a6e22e">print</span>(<span style="color:#e6db74">&#34;Length of absences.y&#34;</span>)
<span style="color:#a6e22e">length</span>(studentdf<span style="color:#f92672">$</span>absences.y)
a <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">is.na</span>(studentdf<span style="color:#f92672">$</span>absences.y)
<span style="color:#a6e22e">print</span>(<span style="color:#e6db74">&#34;Number of NA values in absences.y&#34;</span>)
<span style="color:#a6e22e">length</span>(a[a<span style="color:#f92672">==</span><span style="color:#66d9ef">TRUE</span>])
<span style="color:#a6e22e">print</span>(<span style="color:#e6db74">&#34;Are they equal? how many of different? &#34;</span>)
a <span style="color:#f92672">&lt;-</span> <span style="color:#a6e22e">sort</span>(studentdf<span style="color:#f92672">$</span>absences.x) <span style="color:#f92672">==</span> <span style="color:#a6e22e">sort</span>(studentdf<span style="color:#f92672">$</span>absences.y)
<span style="color:#a6e22e">length</span>(a[a<span style="color:#f92672">==</span><span style="color:#66d9ef">FALSE</span>])
</code></pre></div><pre><code>## [1] &quot;Length of absences.x&quot;
## [1] 382
## [1] &quot;Number of NA values in absences.x&quot;
## [1] 0
## [1] &quot;Length of absences.y&quot;
## [1] 382
## [1] &quot;Number of NA values in absences.y&quot;
## [1] 0
## [1] &quot;Are they equal? how many of different? &quot;
## [1] 210
</code></pre>
<p>pastecs::stat.desc(studentdf(absences, basic=F) tpskew&lt;-semTools::skew(studentdf)absences)
tpkurt&lt;-semTools::kurtosis(studentdf(absences) tpskew[1]/tpskew[2] tpkurt[1]/tpkurt[2] zstabsences&lt;- abs(scale(studentdf)absences))
FSA::perc(as.numeric(zstabsences), 1.96, “gt”)
FSA::perc(as.numeric(zstabsences), 3.29, “gt”)
```</p>
<h2 id="more">More</h2>
<p>Parametric are most powerful, more robuseness becuse we use every score
Parametric or non parametric
pearson for correlation</p>
<p>non para:
spearson kendall
kendall more reilable</p>
<p>Which can I use to compare?</p>
<p>Lecture 5 video 51 minutes</p>
<p>use cooks if deleting outliers</p>
<!-- 5.3. Assumptions of parametric data -->
<!-- alpha 0.05 fo education grades have an error -->
<!-- ok to use this -->
<!-- but in medical testing, more regigroous, 0.05 -->
<h1 id="explore">Explore</h1>
<h1 id="analysis">Analysis</h1>
<h1 id="model">Model</h1>
<h1 id="report">Report</h1>
<h1 id="using-r">Using R</h1>
<h1 id="references">References</h1>
<div id="refs" class="references">
<div id="ref-cortez2008using">
<p>Cortez, Paulo, and Alice Maria Gonçalves Silva. 2008. “Using Data Mining to Predict Secondary School Student Performance.” <a href="http://hdl.handle.net/1822/8024">http://hdl.handle.net/1822/8024</a>.</p>
</div>
<div id="ref-field2012discovering">
<p>Field, A., J. Miles, and Z. Field. 2012. <em>Discovering Statistics Using R</em>. SAGE Publications. <a href="https://books.google.ie/books?id=wd2K2zC3swIC">https://books.google.ie/books?id=wd2K2zC3swIC</a>.</p>
</div>
<div id="ref-wikiportmap">
<p>“Wikipedia.” 2020. Website. <a href="https://en.wikipedia.org/wiki/Portugal">https://en.wikipedia.org/wiki/Portugal</a>.</p>
</div>
</div>

        </div>

        
        
      <hr />
        <div class="row next-prev-navigator">


  
    
    
  

</div>

      <hr />
      
      
          

      
      </div>
    </div>
  </div>
  
</section>


      
      
  <section class="toc-section" id="toc-section">
    
    <div class="toc-holder">
      <h5 class="text-center pl-3">Table of Contents</h5>
      <hr>
      <div class="toc">
        <nav id="TableOfContents">
  <ol>
    <li><a href="#introduction">Introduction</a></li>
    <li><a href="#getting-started">Getting started</a>
      <ol>
        <li><a href="#population-vs-sample">Population vs Sample</a></li>
        <li><a href="#how-to-infer-from-a-sample-to-a-population">How to infer from a sample to a population</a></li>
        <li><a href="#g3---final-grade-ratio">G3 - Final Grade (Ratio)</a>
          <ol>
            <li><a href="#normal-distrubution">Normal Distrubution</a></li>
            <li><a href="#central-tendency">Central Tendency</a></li>
            <li><a href="#dispersion">Dispersion</a></li>
            <li><a href="#confidence-interval">Confidence interval</a></li>
            <li><a href="#z-score">Z-score</a></li>
            <li><a href="#skew-and-kurtosis-analysis">skew and kurtosis analysis</a></li>
            <li><a href="#hypothesis-testing">Hypothesis Testing</a></li>
            <li><a href="#shapirowilk-test">Shapiro–Wilk test</a></li>
            <li><a href="#using-normal-distribution-to-find-outliers">Using Normal Distribution to find outliers</a></li>
            <li><a href="#g3-grades-summary">G3 Grades Summary</a></li>
          </ol>
        </li>
        <li><a href="#reason-nominal">Reason (Nominal)</a></li>
        <li><a href="#studytime-ordinal">Studytime (Ordinal)</a></li>
        <li><a href="#missing-data">Missing Data</a></li>
      </ol>
    </li>
    <li><a href="#relationships">Relationships</a>
      <ol>
        <li><a href="#correlation-absences-and-g3">Correlation (absences and G3)</a></li>
        <li><a href="#more">More</a></li>
      </ol>
    </li>
    <li><a href="#explore">Explore</a></li>
    <li><a href="#analysis">Analysis</a></li>
    <li><a href="#model">Model</a></li>
    <li><a href="#report">Report</a></li>
    <li><a href="#using-r">Using R</a></li>
    <li><a href="#references">References</a></li>
  </ol>
</nav>
      </div>
    </div>
    
  </section>

    </div>

    

  




  




  
  
    
  


<footer class="container-fluid text-center align-content-center footer pb-2">
  <div class="container pt-5">
    <div class="row text-left">
      <div class="col-md-4 col-sm-12">
        <h5>Navigation</h5>
        
        <ul>
            
              
              
                
              
              <li class="nav-item">
                <a class="smooth-scroll" href="#about">About</a>
              </li>
            
            
              
              
                
              
              <li class="nav-item">
                <a class="smooth-scroll" href="#recent-posts">Recent Posts</a>
              </li>
            
        </ul>
        

      </div>
      
      <div class="col-md-4 col-sm-12">
        <h5></h5>
        <ul>
          
        </ul>
      </div>
      
      
    </div>
  </div>
  <hr />
  <div class="container">
    <div class="row text-left">
      <div class="col-md-4">
        <a id="theme" href="https://github.com/hossainemruz/toha" target="#">
          <img src="/blog/assets/images/inverted-logo.png">
          Toha
        </a>
      </div>
      <div class="col-md-4 text-center">© 2020 Copyright.</div>
      <div class="col-md-4 text-right">
        <a id="hugo" href="https://gohugo.io/">Powered by
        <img
          src="/blog/assets/images/hugo-logo-wide.svg"
          alt="Hugo Logo"
          height="18"
        />
        </a>
      </div>
    </div>
  </div>
</footer>

    <script src="/blog/assets/js/jquery-3.4.1.min.js"></script>
<script src="/blog/assets/js/popper.min.js"></script>
<script src="/blog/assets/js/bootstrap.min.js"></script>

<script src="/blog/assets/js/navbar.js"></script>
<script src="/blog/assets/js/main.js"></script>


    
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js"></script>
<script src="/blog/assets/js/single.js"></script>
<script>
  hljs.initHighlightingOnLoad();
</script>


  </body>
</html>
