<!DOCTYPE html>
<html>
  <head>
    <title>Dataset of academic performance evolution</title>
    <meta charset="UTF-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0" />
<meta http-equiv="X-UA-Compatible" content="ie=edge" />


<link rel="stylesheet" href="/blog/assets/css/bootstrap.min.css"/>
<link rel="stylesheet" href="/blog/assets/css/layouts/main.css"/>
<link rel="stylesheet" href="/blog/assets/css/style.css"/>
<link rel="stylesheet" href="/blog/assets/css/navigators/navbar.css"/>


<link href="https://fonts.googleapis.com/css2?family=Muli:wght@300;400;500;600" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" />


<link rel="icon" type="image/png" href="/blog/images/site/favicon.png" />


<link rel="stylesheet" href="/blog/assets/css/style.css"/>



    
<meta name="description" content="Dataset of academic performance evolution" />
<link
  rel="stylesheet"
  href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/10.4.1/highlight.min.js"
/>
<link rel="stylesheet" href="/blog/assets/css/layouts/single.css"/>
<link rel="stylesheet" href="/blog/assets/css/navigators/sidebar.css">


    
    
      
<script type="application/javascript">
var doNotTrack = false;
if (!doNotTrack) {
	window.ga=window.ga||function(){(ga.q=ga.q||[]).push(arguments)};ga.l=+new Date;
	ga('create', 'UA-XXXXXXXXX-X', 'auto');
	
	ga('send', 'pageview');
}
</script>
<script async src='https://www.google-analytics.com/analytics.js'></script>

    
  </head>

  <body data-spy="scroll" data-target="#TableOfContents" data-offset="80">
    <div class="container-fluid bg-dimmed wrapper">
      
      
    


  


  


<nav class="navbar navbar-expand-xl top-navbar final-navbar ">
  <div class="container">
      <button class="navbar-toggler navbar-light" id="sidebar-toggler" type="button" onclick="toggleSidebar()">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="/blog">
      <img src="/blog/images/site/main-logo.png">my ePortfolio</a>
    <button class="navbar-toggler navbar-light" id="toc-toggler" type="button" onclick="toggleTOC()">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse lang-selector" id="top-nav-items">
      <ul class="navbar-nav ml-auto">
      
      </ul>
    </div>
  </div>
  
  <img src="/blog/images/site/main-logo.png" class="d-none" id="main-logo">
  <img src="/blog/images/site/inverted-logo.png" class="d-none" id="inverted-logo">
</nav>



      
      
  <section class="sidebar-section" id="sidebar-section">
    
  </section>


      
      
<section class="content-section" id="content-section">
  <div class="content">
    <div class="container p-0 read-area">
      
      <div class="hero-area col-sm-12" id="hero-area" style='background-image: url(/blog/images/site/library.jpg);'>
      </div>

      
      <div class="page-content">
        <div class="author-profile ml-auto align-self-lg-center">
          <img class="rounded-circle" src='/blog/images/author/brendan.png'/>
          <h5 class="author-name">Brendan</h5>
          <p>January 6, 2021</p>
        </div>

        <div class="title">
          <h1>Dataset of academic performance evolution</h1>
        </div>

        <div class="post-content" id="post-content">
          <table>
<thead>
<tr>
<th>Student Name</th>
<th>Brendan Kent</th>
</tr>
</thead>
<tbody>
<tr>
<td>Student Number</td>
<td>C08861692</td>
</tr>
<tr>
<td>Class</td>
<td>Prob. and Statistical Inference MATH9102</td>
</tr>
<tr>
<td>Course</td>
<td>TU060</td>
</tr>
</tbody>
</table>
<style type="text/css">
.toc .nav-link {
  font-size: 16px;
  line-height: 1;
  padding: 0;
  padding-left: 1;
  transition: all ease-out 0.3s;
  /* color: #1c2d41; */
}

li.nav-item {
    font-size: 16px;
}

pre {
    background-color: #f2f2f2;
#    border-style: ridge;
}

</style>
<h1 id="research-question">Research Question</h1>
<blockquote class="blockquote">
<p>What is the relationship between a student’s overall average score for their professional evaluation in the final year of their professional career
in Engineering and their results obtained in the final year of high
school using two generic high school tests amongst students of Engineering in Columbia. The two tests are Mathematics (MAT_S11) and Critical Reading (CR_S11). Consequently can these predictors be used to predict a student’s overall average score in Engineering by linear regression and which predictors are the most influential.</p>
</blockquote>
<h1 id="dataset">Dataset</h1>
<p>The dataset contains the results in national assessments for secondary and university
education in engineering students and contains academic, social, economic information for 12,411 students.
The data was collected as part of the Master’s Degree in Engineering project of the Technological University of Bolívar (UTB) titled Academic Efficiency Analysis in Engineering students</p>
<p>A full descriptor is available at:
<a href="">https://www.sciencedirect.com/science/article/pii/S2352340920304315#utbl0001</a></p>
<p>The dataset is available for download at <a href="">https://data.mendeley.com/datasets/83tcx8psxv/1</a></p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">df <span style="color:#333">&lt;-</span> <span style="color:#06b;font-weight:bold">read_excel</span>(<span style="background-color:#fff0f0">&#34;data_academic_performance.xlsx&#34;</span>, sheet <span style="color:#333">=</span> <span style="background-color:#fff0f0">&#34;SABER11_SABERPRO&#34;</span>)
</code></pre></div><pre><code>## New names:
## * `` -&gt; ...10
</code></pre>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">df <span style="color:#333">&lt;-</span> df <span style="color:#333">%&gt;%</span> <span style="color:#06b;font-weight:bold">select</span>(<span style="color:#333">-</span><span style="background-color:#fff0f0">&#34;...10&#34;</span>) <span style="color:#888"># deselect this column</span>
</code></pre></div><h2 id="exploring-variables-in-research-question">Exploring variables in research question</h2>
<p>The variable looks clean, no missing records as we can see below. The Saber 11 results are all marked to a maximum of 100 which some students have achieved.</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#888"># ff_glimpse(df)</span>
df <span style="color:#333">%&gt;%</span>
  <span style="color:#06b;font-weight:bold">select</span>(MAT_S11, CR_S11, CC_S11, BIO_S11, ENG_S11, G_SC) <span style="color:#333">%&gt;%</span>
  <span style="color:#06b;font-weight:bold">ff_glimpse</span>()
</code></pre></div><pre><code>## $Continuous
##           label var_type     n missing_n missing_percent  mean   sd  min
## MAT_S11 MAT_S11    &lt;dbl&gt; 12411         0             0.0  64.3 11.9 26.0
## CR_S11   CR_S11    &lt;dbl&gt; 12411         0             0.0  60.8 10.0 24.0
## CC_S11   CC_S11    &lt;dbl&gt; 12411         0             0.0  60.7 10.1  0.0
## BIO_S11 BIO_S11    &lt;dbl&gt; 12411         0             0.0  64.0 11.2 11.0
## ENG_S11 ENG_S11    &lt;dbl&gt; 12411         0             0.0  61.8 14.3 26.0
## G_SC       G_SC    &lt;dbl&gt; 12411         0             0.0 162.7 23.1 37.0
##         quartile_25 median quartile_75   max
## MAT_S11        56.0   64.0        72.0 100.0
## CR_S11         54.0   61.0        67.0 100.0
## CC_S11         54.0   60.0        67.0 100.0
## BIO_S11        56.0   64.0        71.0 100.0
## ENG_S11        50.0   59.0        72.0 100.0
## G_SC          147.0  163.0       179.0 247.0
## 
## $Categorical
## # A tibble: 12,411 x 0
</code></pre>
<ul>
<li>the “level of Measurement” of each of these variables is Ratio, because the value 0 has a meaning.</li>
</ul>
<p>Since I prefer dealing with stardardized score, I will convert all these variables to z-scores.</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">df <span style="color:#333">&lt;-</span> df <span style="color:#333">%&gt;%</span> <span style="color:#06b;font-weight:bold">mutate</span>(scale_MAT_S11 <span style="color:#333">=</span> <span style="color:#06b;font-weight:bold">scale</span>(MAT_S11),
         scale_CR_S11 <span style="color:#333">=</span> <span style="color:#06b;font-weight:bold">scale</span>(CR_S11),
         scale_CC_S11 <span style="color:#333">=</span> <span style="color:#06b;font-weight:bold">scale</span>(CC_S11),
         scale_BIO_S11 <span style="color:#333">=</span> <span style="color:#06b;font-weight:bold">scale</span>(BIO_S11),
         scale_ENG_S11 <span style="color:#333">=</span> <span style="color:#06b;font-weight:bold">scale</span>(ENG_S11),
         scale_G_SC <span style="color:#333">=</span> <span style="color:#06b;font-weight:bold">scale</span>(G_SC))
</code></pre></div><p>Next let’s see the distribution of each:</p>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-5-1.png" alt="Five test results and overall grade in Engineering" width="672" /></p>
<p class="caption">
<p>Figure 1: Five test results and overall grade in Engineering</p>
</p>
</div>
<p>Assessing them for normality and assessing other qualities if not continuous:</p>
<h3 id="mathematics-mat_s11">Mathematics (MAT_S11)</h3>
<pre><code>## skew (g1) 
##  18.17215 
## Excess Kur (g2) 
##        2.954064
</code></pre>
<p>Both skew and kurtosis are high. The cut off is +/- 1.96, anything above this is considered significant. Let’s check the outliers:</p>
<pre><code>## Percentage greater than 1.96 SDs: 4.447667 % 
## Percentage greater than 3.29 SDs: 0 %
</code></pre>
<p>Zero outliers outside the 3.29 SD of mean and less than 5% were outside of 1.96 SD of mean, so we can treat this variable as normal as since the sample size is so large (12411 records).</p>
<p>Report assessment of normality</p>
<blockquote class="blockquote">
<p>Mathematics (MAT_S11) scores was assessed for normality. Visual inspection of the histogram and QQ-Plot (see Figure 1) identified some issues with skewness and kurtosis. The standardised score for kurtosis (2.95) was considered unacceptable using the criteria proposed by West, Finch and Curran (1996), also the standardised score for skewness (18.17) was outside the acceptable range. However 100% of standardised scores for Mathematics (MAT_S11) fall within the bounds of +/- 3.29, using the guidance of Field, Miles and Field (2013) the data can be considered to approximate a normal distribution (m=64.3, sd=11.9, n=12411).</p>
</blockquote>
<h3 id="critical-reading-cr_s11">Critical Reading (CR_S11)</h3>
<pre><code>## skew (g1) 
##   9.74404 
## Excess Kur (g2) 
##        10.86751
</code></pre>
<p>Both skew and kurtosis are high. The cut off is +/- 1.96, anything above this is considered significant. Let’s check the outliers:</p>
<pre><code>## Percentage greater than 1.96 SDs: 5.575699 % 
## Percentage greater than 3.29 SDs: 0.3786963 %
</code></pre>
<p>Almost zero outliers outside the 3.29 SD of mean and about 5% were outside of 1.96 SD of mean, so we can treat this variable as normal as the data set is larger than 80 (12411 records).</p>
<blockquote class="blockquote">
<p>Critical Reading (CR_S11) scores was assessed for normality. Visual inspection of the histogram and QQ-Plot (see Figure 1) identified some issues with skewness and kurtosis. The standardised score for kurtosis (10.87) was considered unacceptable using the criteria proposed by West, Finch and Curran (1996), also the standardised score for skewness (9.74) was outside the acceptable range. However 99.6% of standardised scores for Critical Reading (CR_S11) fall within the bounds of +/- 3.29, using the guidance of Field, Miles and Field (2013) the data can be considered to approximate a normal distribution (m=60.8, sd=10.0, n=12411).</p>
</blockquote>
<h3 id="english-eng_s11">English (ENG_S11)</h3>
<pre><code>## skew (g1) 
##  27.60265 
## Excess Kur (g2) 
##       -8.432497
</code></pre>
<p>Both skew and kurtosis are high. The cut off is +/- 1.96, anything above this is considered significant. Let’s check the outliers:</p>
<pre><code>## Percentage greater than 1.96 SDs: 5.648215 % 
## Percentage greater than 3.29 SDs: 0 %
</code></pre>
<p>Almost zero outliers outside the 3.29 SD of mean and about 5% were outside of 1.96 SD of mean, so we can treat this variable as normal as the data set is larger than 80 (12411 records).</p>
<blockquote class="blockquote">
<p>English (ENG_S11) scores was assessed for normality. Visual inspection of the histogram and QQ-Plot (see Figure 1) identified some issues with skewness and kurtosis. The standardised score for kurtosis (10.87) was considered unacceptable using the criteria proposed by West, Finch and Curran (1996), also the standardised score for skewness (9.74) was outside the acceptable range. However 99.4% of standardised scores for English (ENG_S11) fall within the bounds of +/- 3.29, using the guidance of Field, Miles and Field (2013) the data can be considered to approximate a normal distribution (m=61.8, sd=14.3, n=12411).</p>
</blockquote>
<h3 id="gender-variable">Gender variable</h3>
<p>WE need to access the GENDER variable. It is a variable of type “Nominal”. Let’s take a quick look at a visual:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">df <span style="color:#333">%&gt;%</span>
  <span style="color:#06b;font-weight:bold">ggplot</span>(<span style="color:#06b;font-weight:bold">aes</span>(x<span style="color:#333">=</span>GENDER, y<span style="color:#333">=</span>G_SC, fill<span style="color:#333">=</span>GENDER)) <span style="color:#333">+</span>
    <span style="color:#06b;font-weight:bold">geom_boxplot</span>() <span style="color:#333">+</span>
    <span style="color:#06b;font-weight:bold">scale_fill_viridis</span>(discrete <span style="color:#333">=</span> <span style="color:#080;font-weight:bold">TRUE</span>, alpha<span style="color:#333">=</span><span style="color:#60e;font-weight:bold">0.6</span>) <span style="color:#333">+</span>
    <span style="color:#06b;font-weight:bold">geom_jitter</span>(color<span style="color:#333">=</span><span style="background-color:#fff0f0">&#34;black&#34;</span>, size<span style="color:#333">=</span><span style="color:#60e;font-weight:bold">0.4</span>, alpha<span style="color:#333">=</span><span style="color:#60e;font-weight:bold">0.9</span>) <span style="color:#333">+</span>
    <span style="color:#06b;font-weight:bold">ggtitle</span>(<span style="background-color:#fff0f0">&#34;A boxplot with GENDER and the Overall average score (G_SC)&#34;</span>) <span style="color:#333">+</span>
    <span style="color:#06b;font-weight:bold">ylab</span>(<span style="background-color:#fff0f0">&#34;Overall average score (G_SC) &#34;</span>)
</code></pre></div><p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-12-1.png" width="672" /></p>
<p>stats for GENDER:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">psych<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">describeBy</span>(df<span style="color:#333">$</span>G_SC, df<span style="color:#333">$</span>GENDER, mat<span style="color:#333">=</span><span style="color:#080;font-weight:bold">TRUE</span>)
</code></pre></div><pre><code>##     item group1 vars    n     mean       sd median  trimmed     mad min max
## X11    1      F    1 5043 161.2782 22.33294    162 161.4994 23.7216  76 242
## X12    2      M    1 7368 163.6908 23.58262    164 163.9561 25.2042  37 247
##     range        skew    kurtosis        se
## X11   166 -0.07216008 -0.24717975 0.3144861
## X12   210 -0.12210492  0.01441897 0.2747370
</code></pre>
<h3 id="school-variable">School variable</h3>
<p>We need to access the SCHOOL_NAT variable. It is a variable of type “Nominal”. Let’s take a quick look at a visual:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">df <span style="color:#333">%&gt;%</span>
  <span style="color:#06b;font-weight:bold">ggplot</span>(<span style="color:#06b;font-weight:bold">aes</span>(x<span style="color:#333">=</span>SCHOOL_NAT, y<span style="color:#333">=</span>G_SC, fill<span style="color:#333">=</span>SCHOOL_NAT)) <span style="color:#333">+</span>
    <span style="color:#06b;font-weight:bold">geom_boxplot</span>() <span style="color:#333">+</span>
    <span style="color:#06b;font-weight:bold">scale_fill_viridis</span>(discrete <span style="color:#333">=</span> <span style="color:#080;font-weight:bold">TRUE</span>, alpha<span style="color:#333">=</span><span style="color:#60e;font-weight:bold">0.6</span>) <span style="color:#333">+</span>
    <span style="color:#06b;font-weight:bold">geom_jitter</span>(color<span style="color:#333">=</span><span style="background-color:#fff0f0">&#34;black&#34;</span>, size<span style="color:#333">=</span><span style="color:#60e;font-weight:bold">0.4</span>, alpha<span style="color:#333">=</span><span style="color:#60e;font-weight:bold">0.9</span>) <span style="color:#333">+</span>
    <span style="color:#06b;font-weight:bold">ggtitle</span>(<span style="background-color:#fff0f0">&#34;A boxplot with SCHOOL_NAT and the Overall average score (G_SC)&#34;</span>) <span style="color:#333">+</span>
    <span style="color:#06b;font-weight:bold">ylab</span>(<span style="background-color:#fff0f0">&#34;Overall average score (G_SC) &#34;</span>)
</code></pre></div><p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-14-1.png" width="672" /></p>
<p>stats for SCHOOL_NAT:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">psych<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">describeBy</span>(df<span style="color:#333">$</span>G_SC, df<span style="color:#333">$</span>SCHOOL_NAT, mat<span style="color:#333">=</span><span style="color:#080;font-weight:bold">TRUE</span>)
</code></pre></div><pre><code>##     item  group1 vars    n     mean       sd median  trimmed     mad min max
## X11    1 PRIVATE    1 6565 168.2158 22.82366    170 168.7379 23.7216  37 247
## X12    2  PUBLIC    1 5846 156.5281 21.83817    157 156.5667 22.2390  72 228
##     range        skew    kurtosis        se
## X11   210 -0.20406097  0.02424670 0.2816877
## X12   156 -0.05215938 -0.01912125 0.2856189
</code></pre>
<h3 id="biology-bio_s11">Biology (BIO_S11)</h3>
<pre><code>## skew (g1) 
##   13.7976 
## Excess Kur (g2) 
##        6.800432
</code></pre>
<p>Both skew and kurtosis are high. The cut off is +/- 1.96, anything above this is considered significant. Let’s check the outliers:</p>
<pre><code>## Percentage greater than 1.96 SDs: 5.559584 % 
## Percentage greater than 3.29 SDs: 0.0322295 %
</code></pre>
<p>Almost zero outliers outside the 3.29 SD of mean and about 5% were outside of 1.96 SD of mean, so we can treat this variable as normal as the data set is larger than 80 (12411 records).</p>
<blockquote class="blockquote">
<p>Biology (BIO_S11) scores was assessed for normality. Visual inspection of the histogram and QQ-Plot (see Figure 1) identified some issues with skewness and kurtosis. The standardised score for kurtosis (10.87) was considered unacceptable using the criteria proposed by West, Finch and Curran (1996), also the standardised score for skewness (9.74) was outside the acceptable range. However 99.6% of standardised scores for Biology (BIO_S11) fall within the bounds of +/- 3.29, using the guidance of Field, Miles and Field (2013) the data can be considered to approximate a normal distribution (m=64.0, sd=11.2, n=12411).</p>
</blockquote>
<h3 id="revenue-variable">REVENUE variable</h3>
<p>We need to access the REVENUE variable. It is a variable of type “Ordinal”. Let’s take a quick look at a visual:</p>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-18-1.png" alt="A boxplot with REVENUE and the Overall average score (G_SC)" width="960" /></p>
<p class="caption">
<p>Figure 2: A boxplot with REVENUE and the Overall average score (G_SC)</p>
</p>
</div>
<p>stats for GENDER:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">psych<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">describeBy</span>(df<span style="color:#333">$</span>G_SC, df<span style="color:#333">$</span>REVENUE, mat<span style="color:#333">=</span><span style="color:#080;font-weight:bold">TRUE</span>)
</code></pre></div><pre><code>##     item                          group1 vars    n     mean       sd median
## X11    1                               0    1  279 169.7168 22.63700    172
## X12    2                 10 or more LMMW    1  718 183.6727 20.72211    185
## X13    3  Between 1 and less than 2 LMMW    1 3873 156.7705 22.04578    157
## X14    4  Between 2 and less than 3 LMMW    1 2783 160.9429 21.63347    162
## X15    5  Between 3 and less than 5 LMMW    1 2239 165.3363 22.07567    167
## X16    6  Between 5 and less than 7 LMMW    1  973 170.8602 21.78682    172
## X17    7 Between 7 and less than 10 LMMW    1  509 176.1768 19.96434    178
## X18    8                less than 1 LMMW    1 1037 153.3144 22.01468    153
##      trimmed     mad min max range         skew     kurtosis        se
## X11 170.7244 22.2390  37 228   191 -0.943347983  3.641999614 1.3552419
## X12 184.2622 19.2738 114 246   132 -0.280403866  0.326046072 0.7733424
## X13 156.7670 22.2390  75 237   162 -0.014011136 -0.033082696 0.3542433
## X14 161.2236 22.2390  72 247   175 -0.122777144 -0.096571942 0.4100810
## X15 165.7959 22.2390  91 238   147 -0.170770997 -0.206646615 0.4665377
## X16 171.5212 23.7216  76 239   163 -0.310366669  0.352605142 0.6984535
## X17 176.9487 19.2738 118 240   122 -0.290540077  0.008686752 0.8849039
## X18 153.2575 22.2390  81 226   145  0.003089345 -0.036601838 0.6836331
</code></pre>
<ul>
<li>We can see that students with a REVENUE of zero are under-represented in this data set.</li>
</ul>
<h3 id="school-variable-1">School variable</h3>
<p>We need to access the SCHOOL_NAT variable. It is a variable of type “Nominal”. Let’s take a quick look at a visual:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">df <span style="color:#333">%&gt;%</span>
  <span style="color:#06b;font-weight:bold">ggplot</span>(<span style="color:#06b;font-weight:bold">aes</span>(x<span style="color:#333">=</span>SCHOOL_NAT, y<span style="color:#333">=</span>G_SC, fill<span style="color:#333">=</span>SCHOOL_NAT)) <span style="color:#333">+</span>
    <span style="color:#06b;font-weight:bold">geom_boxplot</span>() <span style="color:#333">+</span>
    <span style="color:#06b;font-weight:bold">scale_fill_viridis</span>(discrete <span style="color:#333">=</span> <span style="color:#080;font-weight:bold">TRUE</span>, alpha<span style="color:#333">=</span><span style="color:#60e;font-weight:bold">0.6</span>) <span style="color:#333">+</span>
    <span style="color:#06b;font-weight:bold">geom_jitter</span>(color<span style="color:#333">=</span><span style="background-color:#fff0f0">&#34;black&#34;</span>, size<span style="color:#333">=</span><span style="color:#60e;font-weight:bold">0.4</span>, alpha<span style="color:#333">=</span><span style="color:#60e;font-weight:bold">0.9</span>) <span style="color:#333">+</span>
    <span style="color:#06b;font-weight:bold">ggtitle</span>(<span style="background-color:#fff0f0">&#34;A boxplot with SCHOOL_NAT and the Overall average score (G_SC)&#34;</span>) <span style="color:#333">+</span>
    <span style="color:#06b;font-weight:bold">ylab</span>(<span style="background-color:#fff0f0">&#34;Overall average score (G_SC) &#34;</span>)
</code></pre></div><p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-20-1.png" width="672" /></p>
<p>stats for SCHOOL_NAT:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">psych<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">describeBy</span>(df<span style="color:#333">$</span>G_SC, df<span style="color:#333">$</span>SCHOOL_NAT, mat<span style="color:#333">=</span><span style="color:#080;font-weight:bold">TRUE</span>)
</code></pre></div><pre><code>##     item  group1 vars    n     mean       sd median  trimmed     mad min max
## X11    1 PRIVATE    1 6565 168.2158 22.82366    170 168.7379 23.7216  37 247
## X12    2  PUBLIC    1 5846 156.5281 21.83817    157 156.5667 22.2390  72 228
##     range        skew    kurtosis        se
## X11   210 -0.20406097  0.02424670 0.2816877
## X12   156 -0.05215938 -0.01912125 0.2856189
</code></pre>
<h1 id="results">Results</h1>
<p>In this section, I will being to put together a model to predict G_SC results.</p>
<h2 id="statistical-evidence">Statistical Evidence</h2>
<p>Before proceeding with linear regression, there are a few assumptions:
1. That there is a relationship, a linear one between the variables
2. Homoscedasticity (we can do this visually or with a test)
3. Independent observations
4. The residual errors should follow a normal distribution (this is the space between the linear line model and the data point)</p>
<p>For 1. we can check that a relationship exists.</p>
<p>Correlation Scatter plot (MAT_S11 and G_SC):</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">df <span style="color:#333">%&gt;%</span>
  <span style="color:#06b;font-weight:bold">ggplot</span>(<span style="color:#06b;font-weight:bold">aes</span>(x<span style="color:#333">=</span>scale_MAT_S11, y<span style="color:#333">=</span>scale_G_SC)) <span style="color:#333">+</span>
  <span style="color:#06b;font-weight:bold">geom_point</span>() <span style="color:#333">+</span> 
  <span style="color:#06b;font-weight:bold">geom_smooth</span>(method <span style="color:#333">=</span> <span style="background-color:#fff0f0">&#34;lm&#34;</span>, colour <span style="color:#333">=</span> <span style="background-color:#fff0f0">&#34;Green&#34;</span>, se <span style="color:#333">=</span> F) <span style="color:#333">+</span> 
  <span style="color:#06b;font-weight:bold">labs</span>(x <span style="color:#333">=</span> <span style="background-color:#fff0f0">&#34;Mathematics (MAT_S11)&#34;</span>, y <span style="color:#333">=</span> <span style="background-color:#fff0f0">&#34;Overall average score (G_SC)&#34;</span>) 
</code></pre></div><pre><code>## `geom_smooth()` using formula 'y ~ x'
</code></pre>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-22-1.png" alt="Correlation Scatter plot (MAT_S11 and G_SC)" width="672" /></p>
<p class="caption">
<p>Figure 3: Correlation Scatter plot (MAT_S11 and G_SC)</p>
</p>
</div>
<p>Doing a Pearson Correlation since both variables are a) continuous b) paired c) independent d) homoscedasticity is present and importantly e) the variables have a normal distribution. Fromt eh plot above, homoscedasticity is ok and we know the data matches the other criteria.</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#888">#Pearson Correlation</span>
<span style="color:#06b;font-weight:bold">cor.test</span>(df<span style="color:#333">$</span>scale_MAT_S11, df<span style="color:#333">$</span>scale_G_SC, method<span style="color:#333">=</span><span style="background-color:#fff0f0">&#39;pearson&#39;</span>)
</code></pre></div><pre><code>## 
##  Pearson's product-moment correlation
## 
## data:  df$scale_MAT_S11 and df$scale_G_SC
## t = 93.733, df = 12409, p-value &lt; 0.00000000000000022
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.6334194 0.6540231
## sample estimates:
##       cor 
## 0.6438379
</code></pre>
<p>The correlation coefficient is a commonly used measure of the size of an effect: values of ±.1 represent a small effect, ±.3 is a medium effect and ±.5 is a large effect</p>
<p>To report Pearson coefficient here we say:</p>
<blockquote class="blockquote">
<p>12411 Mathematics (MAT_S11)(M=64.3, SD=11.9) high school results and a college Engineering overall score(G_SC) (M=162.7, SD=23.1) were investigated. A positive Pearson r correlation coefficient of 0.64 was revealed. There is strong correlation between Mathematics (MAT_S11) results and the college Engineering overall score(G_SC) with t(12409) = 93.733 and a p-value &lt; 0.001. The size of the effect is large.</p>
</blockquote>
<p>Now we know there is a strong relationship between the variables we can begin the model to use Mathematics (MAT_S11) scores to predict Engineering overall scores(G_SC).</p>
<h3 id="simple-linear-regression">Simple Linear Regression</h3>
<p>Let’s check and make sure the single predictor model is the same as the Pearson Correlation.</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">model1<span style="color:#333">&lt;-</span><span style="color:#06b;font-weight:bold">lm</span>(df<span style="color:#333">$</span>scale_G_SC<span style="color:#333">~</span>df<span style="color:#333">$</span>scale_MAT_S11)
<span style="color:#06b;font-weight:bold">anova</span>(model1)
</code></pre></div><pre><code>## Analysis of Variance Table
## 
## Response: df$scale_G_SC
##                     Df Sum Sq Mean Sq F value                Pr(&gt;F)    
## df$scale_MAT_S11     1 5144.3  5144.3  8785.8 &lt; 0.00000000000000022 ***
## Residuals        12409 7265.7     0.6                                  
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
</code></pre>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#06b;font-weight:bold">summary</span>(model1)
</code></pre></div><pre><code>## 
## Call:
## lm(formula = df$scale_G_SC ~ df$scale_MAT_S11)
## 
## Residuals:
##     Min      1Q  Median      3Q     Max 
## -6.2893 -0.4910  0.0195  0.5199  3.6112 
## 
## Coefficients:
##                              Estimate           Std. Error t value
## (Intercept)      0.000000000000002412 0.006868587579970870    0.00
## df$scale_MAT_S11 0.643837935031701836 0.006868864310398667   93.73
##                             Pr(&gt;|t|)    
## (Intercept)                        1    
## df$scale_MAT_S11 &lt;0.0000000000000002 ***
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## Residual standard error: 0.7652 on 12409 degrees of freedom
## Multiple R-squared:  0.4145, Adjusted R-squared:  0.4145 
## F-statistic:  8786 on 1 and 12409 DF,  p-value: &lt; 0.00000000000000022
</code></pre>
<p>Findings:</p>
<ul>
<li>The p-value for ANOVA is exactly the same as the value we got for Pearson (p-value: &lt; 0.00000000000000022).</li>
<li>The ANOVA summary command produces the Multiple R-squared result which is 0.4145, so R = sqrt(0.4145) = 0.64 which is Pearson’s R.</li>
<li>The R squared number can also tell us how much of the variation in G_SC results is explained by MAT_S11. So that’s 41.5 % explained by High School Maths results.</li>
<li>The F-statistic result is (F(1, 12409) = 8786, p &lt; .001), which is statistically significant. We can conclude that this regression model is significantly better at predicting the G_SC scores than if we used the mean value of G_SC.</li>
</ul>
<p>The final thing is to put together the equation of the line with the coefficient.</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#06b;font-weight:bold">coef</span>(model1)
</code></pre></div><pre><code>##             (Intercept)        df$scale_MAT_S11 
## 0.000000000000002412467 0.643837935031701835698
</code></pre>
<p>The z-scale standardized equation is:</p>
<pre><code> G_SC = 0 + 0.64 * MAT_S11
</code></pre><h2 id="mulpile-linear-regression">Mulpile Linear Regression</h2>
<p>Now to add Critical Reading (CR_S11) to out model. Going back to the assumption for linear regression we first need to check for a correlation.</p>
<p>Correlation Scatter plot (MAT_S11 and G_SC):</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">df <span style="color:#333">%&gt;%</span>
  <span style="color:#06b;font-weight:bold">ggplot</span>(<span style="color:#06b;font-weight:bold">aes</span>(x<span style="color:#333">=</span>scale_CR_S11, y<span style="color:#333">=</span>scale_G_SC)) <span style="color:#333">+</span>
  <span style="color:#06b;font-weight:bold">geom_point</span>() <span style="color:#333">+</span> 
  <span style="color:#06b;font-weight:bold">geom_smooth</span>(method <span style="color:#333">=</span> <span style="background-color:#fff0f0">&#34;lm&#34;</span>, colour <span style="color:#333">=</span> <span style="background-color:#fff0f0">&#34;Green&#34;</span>, se <span style="color:#333">=</span> F) <span style="color:#333">+</span> 
  <span style="color:#06b;font-weight:bold">labs</span>(x <span style="color:#333">=</span> <span style="background-color:#fff0f0">&#34;Critical Reading (CR_S11)&#34;</span>, y <span style="color:#333">=</span> <span style="background-color:#fff0f0">&#34;Overall average score (G_SC)&#34;</span>) 
</code></pre></div><pre><code>## `geom_smooth()` using formula 'y ~ x'
</code></pre>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-26-1.png" alt="Correlation Scatter plot (CR_S11 and G_SC)" width="672" /></p>
<p class="caption">
<p>Figure 4: Correlation Scatter plot (CR_S11 and G_SC)</p>
</p>
</div>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#888">#Pearson Correlation</span>
<span style="color:#06b;font-weight:bold">cor.test</span>(df<span style="color:#333">$</span>scale_CR_S11, df<span style="color:#333">$</span>scale_G_SC, method<span style="color:#333">=</span><span style="background-color:#fff0f0">&#39;pearson&#39;</span>)
</code></pre></div><pre><code>## 
##  Pearson's product-moment correlation
## 
## data:  df$scale_CR_S11 and df$scale_G_SC
## t = 96.193, df = 12409, p-value &lt; 0.00000000000000022
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.6433767 0.6635360
## sample estimates:
##       cor 
## 0.6535722
</code></pre>
<p>The correlation coefficient is a commonly used measure of the size of an effect: values of ±.1 represent a small effect, ±.3 is a medium effect and ±.5 is a large effect</p>
<p>The correlation between Critical Reading (CR_S11) and overall score(G_SC) is statistically significant.</p>
<p>To report Pearson coefficient here we say:</p>
<blockquote class="blockquote">
<p>12411 Critical Reading (CR_S11)(M=60.8, SD=10.0) high school results and a college Engineering overall score(G_SC) (M=162.7, SD=23.1) were investigated. A positive Pearson r correlation coefficient of 0.65 was revealed. There is strong correlation between Critical Reading (CR_S11) results and the college Engineering overall score(G_SC) with t(12409) = 96.193 and a p-value &lt; 0.001. The size of the effect is large.</p>
</blockquote>
<p>And now to add it to the first model that add just MAT_S11 to create a extended multiple linear regression model.</p>
<p>A quick look at the simple linear regression model we created again along with adding Critical Reading (CR_S11)</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">model2<span style="color:#333">&lt;-</span><span style="color:#06b;font-weight:bold">lm</span>(df<span style="color:#333">$</span>scale_G_SC<span style="color:#333">~</span>df<span style="color:#333">$</span>scale_MAT_S11<span style="color:#333">+</span>df<span style="color:#333">$</span>scale_CR_S11)
stargazer<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">stargazer</span>(model1, model2, type<span style="color:#333">=</span><span style="background-color:#fff0f0">&#34;text&#34;</span>)
</code></pre></div><pre><code>## 
## =============================================================================
##                                        Dependent variable:                   
##                     ---------------------------------------------------------
##                                            scale_G_SC                        
##                                 (1)                          (2)             
## -----------------------------------------------------------------------------
## scale_MAT_S11                 0.644***                     0.390***          
##                               (0.007)                      (0.008)           
##                                                                              
## scale_CR_S11                                               0.415***          
##                                                            (0.008)           
##                                                                              
## Constant                       0.000                        0.000            
##                               (0.007)                      (0.006)           
##                                                                              
## -----------------------------------------------------------------------------
## Observations                   12,411                       12,411           
## R2                             0.415                        0.523            
## Adjusted R2                    0.414                        0.523            
## Residual Std. Error      0.765 (df = 12409)           0.691 (df = 12408)     
## F Statistic         8,785.839*** (df = 1; 12409) 6,799.872*** (df = 2; 12408)
## =============================================================================
## Note:                                             *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01
</code></pre>
<p>Some outcomes from model 2</p>
<ul>
<li>The Adjusted R squared has improved from 0.4145 to 0.523, meaning we can now explain more of variation in G_SC by including CR_S11 into our model</li>
<li>CR_S11 is statically significant to p&lt;0.01.</li>
</ul>
<p>One of the assumptions of a multiple linear regression model is that the residuals follow a normal distribution. We need to check this now on our model2. We can do this by finding any influential outliers by using cook’s distance.</p>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-29-1.png" alt="Cook's D for model2" width="672" /></p>
<p class="caption">
<p>Figure 5: Cook’s D for model2</p>
</p>
</div>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-30-1.png" alt="Cook's D for model2" width="672" /></p>
<p class="caption">
<p>Figure 6: Cook’s D for model2</p>
</p>
</div>
<ul>
<li>According to (Stephanie <a href="#ref-stephanie_2018">2018</a>), a general rule of thumb is that observations with a Cook’s D of more than 3 times the mean, is a possible outlier. In the figure above, in red we have the values which are greater than 4 times the mean Cook’s D.</li>
</ul>
<p>Now to find rows related to influential observations, the ones above the line in the above figure:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">influential <span style="color:#333">&lt;-</span> <span style="color:#06b;font-weight:bold">as.numeric</span>(<span style="color:#06b;font-weight:bold">names</span>(cooksd)<span style="color:#06b;font-weight:bold">[</span>(cooksd <span style="color:#333">&gt;</span> <span style="color:#60e;font-weight:bold">4</span><span style="color:#333">*</span><span style="color:#06b;font-weight:bold">mean</span>(cooksd, na.rm<span style="color:#333">=</span>T))])  <span style="color:#888"># influential row numbers</span>
<span style="color:#06b;font-weight:bold">cat</span>(<span style="background-color:#fff0f0">&#34;Number of influencers:&#34;</span>, <span style="color:#06b;font-weight:bold">length</span>(influential), <span style="background-color:#fff0f0">&#34;\n&#34;</span>)
</code></pre></div><pre><code>## Number of influencers: 595
</code></pre>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#06b;font-weight:bold">cat </span>(<span style="background-color:#fff0f0">&#34;20 influencers in MAT_S11&#34;</span>,<span style="color:#06b;font-weight:bold">head</span>(df[influential, ]<span style="color:#333">$</span>MAT_S11, n <span style="color:#333">=</span> <span style="color:#60e;font-weight:bold">20</span>),<span style="background-color:#fff0f0">&#34;\n&#34;</span>)
</code></pre></div><pre><code>## 20 influencers in MAT_S11 45 56 78 56 73 70 52 56 48 67 54 77 70 52 66 76 51 49 92 81
</code></pre>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#06b;font-weight:bold">cat </span>(<span style="background-color:#fff0f0">&#34;20 influencers in CR_S11&#34;</span>,<span style="color:#06b;font-weight:bold">head</span>(df[influential, ]<span style="color:#333">$</span>CR_S11, n <span style="color:#333">=</span> <span style="color:#60e;font-weight:bold">20</span>),<span style="background-color:#fff0f0">&#34;\n&#34;</span>)
</code></pre></div><pre><code>## 20 influencers in CR_S11 51 47 77 39 54 54 58 62 41 61 61 71 48 50 47 74 54 57 65 56
</code></pre>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#06b;font-weight:bold">cat </span>(<span style="background-color:#fff0f0">&#34;Percentage of influencers: &#34;</span>, (<span style="color:#06b;font-weight:bold">length</span>(influential) <span style="color:#333">/</span> <span style="color:#06b;font-weight:bold">nrow</span>(df)) <span style="color:#333">*</span> <span style="color:#60e;font-weight:bold">100</span>, <span style="background-color:#fff0f0">&#34;% \n&#34;</span>)
</code></pre></div><pre><code>## Percentage of influencers:  4.794134 %
</code></pre>
<p>The total number of influential observations is less than 5% of the total.</p>
<p>Bonferonni p-value for most extreme obs - Are there any cases where the outcome variable has an unusual variable for its predictor values?</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">car<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">outlierTest</span>(model2)
</code></pre></div><pre><code>##        rstudent        unadjusted p-value          Bonferroni p
## 1336  -8.963117 0.00000000000000000036042 0.0000000000000044731
## 7721  -5.540430 0.00000003078800000000000 0.0003821100000000000
## 3718  -5.249445 0.00000015508000000000001 0.0019246999999999999
## 204   -5.125972 0.00000030045999999999998 0.0037290000000000001
## 12376  5.097221 0.00000034975000000000002 0.0043407000000000003
## 1281   5.039005 0.00000047455000000000002 0.0058896000000000000
## 12069 -4.740949 0.00000215079999999999980 0.0266939999999999990
</code></pre>
<ul>
<li>our model2 is telling us that these values above are unusual variables with very statistically significant results</li>
</ul>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-33-1.png" alt="leverage plots for model2" width="672" /></p>
<p class="caption">
<p>Figure 7: leverage plots for model2</p>
</p>
</div>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-34-1.png" alt="Assess homocedasticity for model2" width="672" /></p>
<p class="caption">
<p>Figure 8: Assess homocedasticity for model2</p>
</p>
</div>
<ul>
<li>We can see there is absolutely no heteroscedastity, we see a completely random, equal distribution of points throughout the range of X axis and a flat red line. There is no pattern in the residuals.</li>
</ul>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-35-1.png" alt="Histogram and density plot of the residuals for model2" width="672" /></p>
<p class="caption">
<p>Figure 9: Histogram and density plot of the residuals for model2</p>
</p>
</div>
<ul>
<li>we have a good normal distribution of the residuals.</li>
</ul>
<!-- end list -->
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">residuals <span style="color:#333">&lt;-</span> <span style="color:#06b;font-weight:bold">residuals</span>(model2)
resids<span style="color:#333">&lt;-</span> <span style="color:#06b;font-weight:bold">abs</span>(residuals)
<span style="color:#06b;font-weight:bold">cat</span>(<span style="background-color:#fff0f0">&#34;Percentage greater than 1.96 SDs:&#34;</span>, FSA<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">perc</span>(<span style="color:#06b;font-weight:bold">as.numeric</span>(resids), <span style="color:#60e;font-weight:bold">1.96</span>, <span style="background-color:#fff0f0">&#34;gt&#34;</span>),<span style="background-color:#fff0f0">&#34;% \n&#34;</span>)
</code></pre></div><pre><code>## Percentage greater than 1.96 SDs: 0.9910563 %
</code></pre>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#06b;font-weight:bold">cat</span>(<span style="background-color:#fff0f0">&#34;Percentage greater than 3.29 SDs:&#34;</span>,FSA<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">perc</span>(<span style="color:#06b;font-weight:bold">as.numeric</span>(resids), <span style="color:#60e;font-weight:bold">3.29</span>, <span style="background-color:#fff0f0">&#34;gt&#34;</span>), <span style="background-color:#fff0f0">&#34;%&#34;</span>)
</code></pre></div><pre><code>## Percentage greater than 3.29 SDs: 0.0483442 %
</code></pre>
<ul>
<li>almost 0% outliers at 3.29 standards deviations from mean and for a data set this size. We can accept the distribution as normal.</li>
</ul>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-37-1.png" alt="QQ plot of the residuals for model2" width="672" /></p>
<p class="caption">
<p>Figure 10: QQ plot of the residuals for model2</p>
</p>
</div>
<pre><code>## [1] 1336 7721
</code></pre>
<p>We now need to check for Collinearity in our model.</p>
<h3 id="collinearity">Collinearity:</h3>
<p>Calculate Collinearity:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">vifmodel<span style="color:#333">&lt;-</span>car<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">vif</span>(model2)
vifmodel
</code></pre></div><pre><code>## df$scale_MAT_S11  df$scale_CR_S11 
##         1.592284         1.592284
</code></pre>
<ul>
<li>As a rule of thumb, a VIF score over 5 is a problem. A score over 10 should be remedied and you should consider dropping the problematic variable from the regression model</li>
</ul>
<p>Calculate tolerance:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#60e;font-weight:bold">1</span><span style="color:#333">/</span>vifmodel
</code></pre></div><pre><code>## df$scale_MAT_S11  df$scale_CR_S11 
##        0.6280287        0.6280287
</code></pre>
<ul>
<li>
<p>If the VIF value is greater than 2.5 or the Tolerance is less than 0.4, then you have concerns over multicollinearity.</p>
</li>
<li>
<p>Collinearity occurs when two or more independent variables are giving the same information, one could be redundant.</p>
</li>
<li>
<p>To check collinearity, we examine the correlation matrix that compares the independent variables with each other.</p>
</li>
<li>
<p>If we get a correlation coefficient of above 0.8, then we may have collinearity.</p>
</li>
</ul>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-40-1.png" alt="correlation matrix for model2" width="672" /></p>
<p class="caption">
<p>Figure 11: correlation matrix for model2</p>
</p>
</div>
<ul>
<li>the result from our correlation matrix for model2 show that these variables have a correlation less than 0.8, so we don’t have collinearity.</li>
</ul>
<p>Reporting:</p>
<blockquote class="blockquote">
<p>Tests to see if the data met the assumption of collinearity indicated that multicollinearity was not a concern (MAT_S11, Tolerance = .63, VIF = 1.6; CR_S11, Tolerance = .63 VIF = 1.6).</p>
</blockquote>
<h3 id="muliple-lienar-regression-checks">Muliple Lienar regression checks</h3>
<p>Association:</p>
<ul>
<li>For MLR (multi-linear regressions), we must have some proof there is an actually real link between these variables used as predictors and the outcome variable. We can use test statistics as we have seen in the previous sections for this. We have shown this earlier.</li>
</ul>
<p>Time Order:</p>
<ul>
<li>making sure the predictor happens before the outcome variable, this high school data is definitely before the engineering results.</li>
</ul>
<p>Non-spuriousness:</p>
<ul>
<li>Try to reduce spurious relationships, relationships that are just a coincidence, don’t leave out key predictors, even if they are not significant, because they may interact with the predictors.</li>
</ul>
<p>Outcome variable:</p>
<ul>
<li>Must be continuous which G_SC</li>
</ul>
<h3 id="reporting-my-model">Reporting my model</h3>
<blockquote class="blockquote">
<p>A multiple regression analysis was conducted to determine if a student’s high school Mathematics (MAT_S11) score and high school Critical Reading (CR_S11) score could predict a student’s Overall average score (G_SC) in Engineering in college.</p>
<p>Examination of the histogram, normal Q-Q plots of standardized residuals and the scatterplot of the dependent variable, academic satisfaction, and standardized residuals showed that the some outliers existed. However, examination of the standardized residuals showed that none could be considered to have undue influence (95% within limits of -3.29 to plus 3.29 and less than 5% with a Cook’s distance three times the mean.</p>
<p>Examination for multicollinearity showed that the tolerance and variance influence factor measures were within acceptable levels (tolerance &gt;0.4, VIF &lt;2.5 ) as outlined in Tarling (2008). The scatterplot of standardized residuals showed that the data met the assumptions of homogeneity of variance and linearity. The data also meets the assumption of non-zero variances of the predictors.</p>
</blockquote>
<p>The z-scale standardized equation of model2 is:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#06b;font-weight:bold">coef</span>(model2)
</code></pre></div><pre><code>##             (Intercept)        df$scale_MAT_S11         df$scale_CR_S11 
## 0.000000000000001828726 0.390472346583577545331 0.415425295946089234711
</code></pre>
<pre><code> G_SC = 0 + 0.39 * MAT_S11 + 0.42 * CR_S11
</code></pre><ul>
<li>explaining 52.3% of the variation in G_SC</li>
</ul>
<h2 id="adding-gender">Adding GENDER</h2>
<p>Let’s check for a relationship between GENDER and G_SC before adding it to our model.</p>
<p>I will do a simple t-test.</p>
<p>I will state the two hypothesis for this test:</p>
<p>H<sub>0</sub>: There is no difference in G_SC results for a female in comparison to a male</p>
<p>H<sub>a</sub>: There is a difference in G_SC results for a female in comparison to a male</p>
<p>We now first conduct Levene’s test for homogeneity of variance</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">car<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">leveneTest</span>(G_SC <span style="color:#333">~</span> GENDER, data<span style="color:#333">=</span>df)
</code></pre></div><pre><code>## Warning in leveneTest.default(y = y, group = group, ...): group coerced to
## factor.

## Levene's Test for Homogeneity of Variance (center = median)
##          Df F value   Pr(&gt;F)    
## group     1  13.115 0.000294 ***
##       12409                     
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
</code></pre>
<p>The statistical hypotheses for Levene’s Test are:
Null hypothesis (H<sub>0</sub>): the variances of the two groups are equal.
Alternative hypothesis (H<sub>a</sub>): the variances are different.</p>
<p>The variances are different from the Levene’s Test so we cannot use GENDER.</p>
<h2 id="adding-school_nat">Adding SCHOOL_NAT</h2>
<p>Let’s check for a relationship between SCHOOL_NAT and G_SC before adding it to our model.</p>
<p>I will do a simple t-test.</p>
<p>I will state the two hypothesis for this test:</p>
<p>H<sub>0</sub>: There is no difference in G_SC results for a student in private school to one in public school</p>
<p>H<sub>a</sub>: There is a difference in G_SC results for a student in private school to one in public school</p>
<p>We now first conduct Levene’s test for homogeneity of variance</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">car<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">leveneTest</span>(G_SC <span style="color:#333">~</span> SCHOOL_NAT, data<span style="color:#333">=</span>df)
</code></pre></div><pre><code>## Warning in leveneTest.default(y = y, group = group, ...): group coerced to
## factor.

## Levene's Test for Homogeneity of Variance (center = median)
##          Df F value    Pr(&gt;F)    
## group     1  12.614 0.0003843 ***
##       12409                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
</code></pre>
<p>The statistical hypotheses for Levene’s Test are:
Null hypothesis (H<sub>0</sub>): the variances of the two groups are equal.
Alternative hypothesis (H<sub>a</sub>): the variances are different.</p>
<p>The test result is significant and so we can reject the Null and these populations variances are different.</p>
<p>I will not add it to the model.</p>
<h2 id="adding-biology-bio_s11">Adding Biology (BIO_S11)</h2>
<p>Correlation Scatter plot (BIO_S11 and G_SC):</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">df <span style="color:#333">%&gt;%</span>
  <span style="color:#06b;font-weight:bold">ggplot</span>(<span style="color:#06b;font-weight:bold">aes</span>(x<span style="color:#333">=</span>scale_BIO_S11, y<span style="color:#333">=</span>scale_G_SC)) <span style="color:#333">+</span>
  <span style="color:#06b;font-weight:bold">geom_point</span>() <span style="color:#333">+</span> 
  <span style="color:#06b;font-weight:bold">geom_smooth</span>(method <span style="color:#333">=</span> <span style="background-color:#fff0f0">&#34;lm&#34;</span>, colour <span style="color:#333">=</span> <span style="background-color:#fff0f0">&#34;Green&#34;</span>, se <span style="color:#333">=</span> F) <span style="color:#333">+</span> 
  <span style="color:#06b;font-weight:bold">labs</span>(x <span style="color:#333">=</span> <span style="background-color:#fff0f0">&#34;Biology (BIO_S11)&#34;</span>, y <span style="color:#333">=</span> <span style="background-color:#fff0f0">&#34;Overall average score (G_SC)&#34;</span>) 
</code></pre></div><pre><code>## `geom_smooth()` using formula 'y ~ x'
</code></pre>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-44-1.png" alt="Correlation Scatter plot (BIO_S11 and G_SC)" width="672" /></p>
<p class="caption">
<p>Figure 12: Correlation Scatter plot (BIO_S11 and G_SC)</p>
</p>
</div>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#888">#Pearson Correlation</span>
<span style="color:#06b;font-weight:bold">cor.test</span>(df<span style="color:#333">$</span>scale_BIO_S11, df<span style="color:#333">$</span>scale_G_SC, method<span style="color:#333">=</span><span style="background-color:#fff0f0">&#39;pearson&#39;</span>)
</code></pre></div><pre><code>## 
##  Pearson's product-moment correlation
## 
## data:  df$scale_BIO_S11 and df$scale_G_SC
## t = 99.627, df = 12409, p-value &lt; 0.00000000000000022
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.6567441 0.6762966
## sample estimates:
##      cor 
## 0.666635
</code></pre>
<p>The correlation coefficient is a commonly used measure of the size of an effect: values of ±.1 represent a small effect, ±.3 is a medium effect and ±.5 is a large effect</p>
<p>The correlation between Biology (BIO_S11) and overall score(G_SC) is statistically significant.</p>
<p>To report Pearson coefficient here we say:</p>
<blockquote class="blockquote">
<p>12411 Biology (BIO_S11)(M=64.0, SD=11.2) high school results and a college Engineering overall score(G_SC) (M=162.7, SD=23.1) were investigated. A positive Pearson r correlation coefficient of 0.67 was revealed. There is strong correlation between Biology (BIO_S11) results and the college Engineering overall score(G_SC) with t(12409) = 99.62 and a p-value &lt; 0.001. The size of the effect is large.</p>
</blockquote>
<p>Creating a new model with Biology (BIO_S11)</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">model3<span style="color:#333">&lt;-</span><span style="color:#06b;font-weight:bold">lm</span>(df<span style="color:#333">$</span>scale_G_SC<span style="color:#333">~</span>df<span style="color:#333">$</span>scale_MAT_S11<span style="color:#333">+</span>df<span style="color:#333">$</span>scale_CR_S11<span style="color:#333">+</span>df<span style="color:#333">$</span>scale_BIO_S11)
stargazer<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">stargazer</span>(model1, model2, model3, type<span style="color:#333">=</span><span style="background-color:#fff0f0">&#34;text&#34;</span>)
</code></pre></div><pre><code>## 
## ==========================================================================================================
##                                                      Dependent variable:                                  
##                     --------------------------------------------------------------------------------------
##                                                           scale_G_SC                                      
##                                 (1)                          (2)                          (3)             
## ----------------------------------------------------------------------------------------------------------
## scale_MAT_S11                 0.644***                     0.390***                     0.240***          
##                               (0.007)                      (0.008)                      (0.010)           
##                                                                                                           
## scale_CR_S11                                               0.415***                     0.333***          
##                                                            (0.008)                      (0.008)           
##                                                                                                           
## scale_BIO_S11                                                                           0.263***          
##                                                                                         (0.010)           
##                                                                                                           
## Constant                       0.000                        0.000                        0.000            
##                               (0.007)                      (0.006)                      (0.006)           
##                                                                                                           
## ----------------------------------------------------------------------------------------------------------
## Observations                   12,411                       12,411                       12,411           
## R2                             0.415                        0.523                        0.548            
## Adjusted R2                    0.414                        0.523                        0.547            
## Residual Std. Error      0.765 (df = 12409)           0.691 (df = 12408)           0.673 (df = 12407)     
## F Statistic         8,785.839*** (df = 1; 12409) 6,799.872*** (df = 2; 12408) 5,006.006*** (df = 3; 12407)
## ==========================================================================================================
## Note:                                                                          *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01
</code></pre>
<p>Some outcomes from model 3:</p>
<ul>
<li>The Adjusted R squared has improved from 0.4145 to 0.523 and now to 0.547, meaning we can now explain more of variation in G_SC by including BIO_S11 into our model</li>
<li>BIO_S11 is statically significant to p&lt;0.01.</li>
</ul>
<p>One of the assumptions of a multiple linear regression model is that the residuals follow a normal distribution. We need to check this now on our model2. We can do this by finding any influential outliers by using cook’s distance.</p>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-47-1.png" alt="Cook's D for model3" width="672" /></p>
<p class="caption">
<p>Figure 13: Cook’s D for model3</p>
</p>
</div>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">influential <span style="color:#333">&lt;-</span> <span style="color:#06b;font-weight:bold">as.numeric</span>(<span style="color:#06b;font-weight:bold">names</span>(cooksd)<span style="color:#06b;font-weight:bold">[</span>(cooksd <span style="color:#333">&gt;</span> <span style="color:#60e;font-weight:bold">4</span><span style="color:#333">*</span><span style="color:#06b;font-weight:bold">mean</span>(cooksd, na.rm<span style="color:#333">=</span>T))])  <span style="color:#888"># influential row numbers</span>
<span style="color:#06b;font-weight:bold">cat</span>(<span style="background-color:#fff0f0">&#34;Number of influencers:&#34;</span>, <span style="color:#06b;font-weight:bold">length</span>(influential), <span style="background-color:#fff0f0">&#34;\n&#34;</span>)
</code></pre></div><pre><code>## Number of influencers: 588
</code></pre>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#06b;font-weight:bold">cat </span>(<span style="background-color:#fff0f0">&#34;20 influencers in MAT_S11&#34;</span>,<span style="color:#06b;font-weight:bold">head</span>(df[influential, ]<span style="color:#333">$</span>MAT_S11, n <span style="color:#333">=</span> <span style="color:#60e;font-weight:bold">20</span>),<span style="background-color:#fff0f0">&#34;\n&#34;</span>)
</code></pre></div><pre><code>## 20 influencers in MAT_S11 71 58 71 51 40 58 80 70 57 60 51 77 56 65 53 69 87 73 77 71
</code></pre>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#06b;font-weight:bold">cat </span>(<span style="background-color:#fff0f0">&#34;20 influencers in CR_S11&#34;</span>,<span style="color:#06b;font-weight:bold">head</span>(df[influential, ]<span style="color:#333">$</span>CR_S11, n <span style="color:#333">=</span> <span style="color:#60e;font-weight:bold">20</span>),<span style="background-color:#fff0f0">&#34;\n&#34;</span>)
</code></pre></div><pre><code>## 20 influencers in CR_S11 74 67 95 50 54 64 51 52 56 54 67 54 62 81 42 55 67 69 64 78
</code></pre>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#06b;font-weight:bold">cat </span>(<span style="background-color:#fff0f0">&#34;Percentage of influencers: &#34;</span>, (<span style="color:#06b;font-weight:bold">length</span>(influential) <span style="color:#333">/</span> <span style="color:#06b;font-weight:bold">nrow</span>(df)) <span style="color:#333">*</span> <span style="color:#60e;font-weight:bold">100</span>, <span style="background-color:#fff0f0">&#34;% \n&#34;</span>)
</code></pre></div><pre><code>## Percentage of influencers:  4.737733 %
</code></pre>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-49-1.png" alt="Cook's D for model3" width="672" /></p>
<p class="caption">
<p>Figure 14: Cook’s D for model3</p>
</p>
</div>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-50-1.png" alt="Assess homocedasticity for model3" width="672" /></p>
<p class="caption">
<p>Figure 15: Assess homocedasticity for model3</p>
</p>
</div>
<ul>
<li>We can see there is absolutely no heteroscedastity, we see a completely random, equal distribution of points throughout the range of X axis and a flat red line. There is no pattern in the residuals.</li>
</ul>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-51-1.png" alt="Histogram and density plot of the residuals for model3" width="672" /></p>
<p class="caption">
<p>Figure 16: Histogram and density plot of the residuals for model3</p>
</p>
</div>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">residuals <span style="color:#333">&lt;-</span> <span style="color:#06b;font-weight:bold">residuals</span>(model3)
resids<span style="color:#333">&lt;-</span> <span style="color:#06b;font-weight:bold">abs</span>(residuals)
<span style="color:#06b;font-weight:bold">cat</span>(<span style="background-color:#fff0f0">&#34;Percentage greater than 1.96 SDs:&#34;</span>, FSA<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">perc</span>(<span style="color:#06b;font-weight:bold">as.numeric</span>(resids), <span style="color:#60e;font-weight:bold">1.96</span>, <span style="background-color:#fff0f0">&#34;gt&#34;</span>),<span style="background-color:#fff0f0">&#34;% \n&#34;</span>)
</code></pre></div><pre><code>## Percentage greater than 1.96 SDs: 0.8621384 %
</code></pre>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#06b;font-weight:bold">cat</span>(<span style="background-color:#fff0f0">&#34;Percentage greater than 3.29 SDs:&#34;</span>,FSA<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">perc</span>(<span style="color:#06b;font-weight:bold">as.numeric</span>(resids), <span style="color:#60e;font-weight:bold">3.29</span>, <span style="background-color:#fff0f0">&#34;gt&#34;</span>), <span style="background-color:#fff0f0">&#34;%&#34;</span>)
</code></pre></div><pre><code>## Percentage greater than 3.29 SDs: 0.0402868 %
</code></pre>
<ul>
<li>almost 0% outliers at 3.29 standards deviations from mean and for a data set this size. We can accept the distribution as normal.</li>
</ul>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-53-1.png" alt="QQ plot of the residuals for model3" width="672" /></p>
<p class="caption">
<p>Figure 17: QQ plot of the residuals for model3</p>
</p>
</div>
<pre><code>## [1]  1336 12376
</code></pre>
<p>We now need to check for Collinearity in our model3.</p>
<h3 id="collinearity-1">Collinearity:</h3>
<p>Calculate Collinearity:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">vifmodel<span style="color:#333">&lt;-</span>car<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">vif</span>(model3)
vifmodel
</code></pre></div><pre><code>## df$scale_MAT_S11  df$scale_CR_S11 df$scale_BIO_S11 
##         2.511959         1.866286         2.805998
</code></pre>
<ul>
<li>As a rule of thumb, a VIF score over 5 is a problem. A score over 10 should be remedied and you should consider dropping the problematic variable from the regression model</li>
</ul>
<p>Calculate tolerance:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#60e;font-weight:bold">1</span><span style="color:#333">/</span>vifmodel
</code></pre></div><pre><code>## df$scale_MAT_S11  df$scale_CR_S11 df$scale_BIO_S11 
##        0.3980957        0.5358235        0.3563794
</code></pre>
<ul>
<li>
<p>If the VIF value is greater than 2.5 or the Tolerance is less than 0.4, then you have concerns over multicollinearity.</p>
</li>
<li>
<p>Collinearity occurs when two or more independent variables are giving the same information, one could be redundant.</p>
</li>
<li>
<p>To check collinearity, we examine the correlation matrix that compares the independent variables with each other.</p>
</li>
<li>
<p>If we get a correlation coefficient of above 0.8, then we may have collinearity.</p>
</li>
</ul>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-56-1.png" alt="correlation matrix for model3" width="672" /></p>
<p class="caption">
<p>Figure 18: correlation matrix for model3</p>
</p>
</div>
<ul>
<li>the result from our correlation matrix for model2 show that these variables have a correlation less than 0.8, so we don’t have collinearity.</li>
</ul>
<p>Reporting:</p>
<blockquote class="blockquote">
<p>Tests to see if the data met the assumption of collinearity indicated that multicollinearity was a concern for BIO_S11 results (MAT_S11, Tolerance = .63, VIF = 1.6; CR_S11, Tolerance = .63 VIF = 1.6; BIO_S11, Tolerance = .35 VIF = 2.80).</p>
</blockquote>
<p>Therefore BIO_S11 cannot be added to the model. We do not need any further tests.</p>
<h2 id="adding-revenue">Adding REVENUE</h2>
<p>Let’s check the relationship between REVENUE and G_SC.</p>
<p>First, I need to test for homogeneity of variance. Using Levene’s test, our Null hypothesis is that there is no difference in variance.</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">car<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">leveneTest</span>(G_SC <span style="color:#333">~</span> REVENUE, data<span style="color:#333">=</span>df)
</code></pre></div><pre><code>## Warning in leveneTest.default(y = y, group = group, ...): group coerced to
## factor.

## Levene's Test for Homogeneity of Variance (center = median)
##          Df F value  Pr(&gt;F)   
## group     7  2.7166 0.00817 **
##       12403                   
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
</code></pre>
<ul>
<li>The null hypothesis is rejected and so we can not consider the data to have homogeneity of variance and therefore cannot use it in our model.</li>
</ul>
<p>Checking Bartlett’s test for homogeneity of variance also:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">stats<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">bartlett.test</span>(G_SC<span style="color:#333">~</span> REVENUE, data<span style="color:#333">=</span>df)
</code></pre></div><pre><code>## 
##  Bartlett test of homogeneity of variances
## 
## data:  G_SC by REVENUE
## Bartlett's K-squared = 14.006, df = 7, p-value = 0.05108
</code></pre>
<ul>
<li>again result is statistically significant and so we reject the null hypothesis again.</li>
</ul>
<h2 id="adding-english-eng_s11">Adding English (ENG_S11)</h2>
<p>Correlation Scatter plot (ENG_S11 and G_SC):</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">df <span style="color:#333">%&gt;%</span>
  <span style="color:#06b;font-weight:bold">ggplot</span>(<span style="color:#06b;font-weight:bold">aes</span>(x<span style="color:#333">=</span>scale_ENG_S11, y<span style="color:#333">=</span>scale_G_SC)) <span style="color:#333">+</span>
  <span style="color:#06b;font-weight:bold">geom_point</span>() <span style="color:#333">+</span> 
  <span style="color:#06b;font-weight:bold">geom_smooth</span>(method <span style="color:#333">=</span> <span style="background-color:#fff0f0">&#34;lm&#34;</span>, colour <span style="color:#333">=</span> <span style="background-color:#fff0f0">&#34;Green&#34;</span>, se <span style="color:#333">=</span> F) <span style="color:#333">+</span> 
  <span style="color:#06b;font-weight:bold">labs</span>(x <span style="color:#333">=</span> <span style="background-color:#fff0f0">&#34;English (ENG_S11)&#34;</span>, y <span style="color:#333">=</span> <span style="background-color:#fff0f0">&#34;Overall average score (G_SC)&#34;</span>) 
</code></pre></div><pre><code>## `geom_smooth()` using formula 'y ~ x'
</code></pre>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-59-1.png" alt="Correlation Scatter plot (ENG_S11 and G_SC)" width="672" /></p>
<p class="caption">
<p>Figure 19: Correlation Scatter plot (ENG_S11 and G_SC)</p>
</p>
</div>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#888">#Pearson Correlation</span>
<span style="color:#06b;font-weight:bold">cor.test</span>(df<span style="color:#333">$</span>scale_ENG_S11, df<span style="color:#333">$</span>scale_G_SC, method<span style="color:#333">=</span><span style="background-color:#fff0f0">&#39;pearson&#39;</span>)
</code></pre></div><pre><code>## 
##  Pearson's product-moment correlation
## 
## data:  df$scale_ENG_S11 and df$scale_G_SC
## t = 98.435, df = 12409, p-value &lt; 0.00000000000000022
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.6521731 0.6719345
## sample estimates:
##       cor 
## 0.6621689
</code></pre>
<p>The correlation coefficient is a commonly used measure of the size of an effect: values of ±.1 represent a small effect, ±.3 is a medium effect and ±.5 is a large effect</p>
<p>The correlation between English (ENG_S11) and overall score(G_SC) is statistically significant.</p>
<p>To report Pearson coefficient here we say:</p>
<blockquote class="blockquote">
<p>12411 English (ENG_S11)(M=61.8, SD=14.3) high school results and a college Engineering overall score(G_SC) (M=162.7, SD=23.1) were investigated. A positive Pearson r correlation coefficient of 0.67 was revealed. There is strong correlation between English (ENG_S11) results and the college Engineering overall score(G_SC) with t(12409) = 98.4 and a p-value &lt; 0.001. The size of the effect is large.</p>
</blockquote>
<p>Creating a new model4 with English (ENG_S11)</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">model4<span style="color:#333">&lt;-</span><span style="color:#06b;font-weight:bold">lm</span>(df<span style="color:#333">$</span>scale_G_SC<span style="color:#333">~</span>df<span style="color:#333">$</span>scale_MAT_S11<span style="color:#333">+</span>df<span style="color:#333">$</span>scale_CR_S11<span style="color:#333">+</span>df<span style="color:#333">$</span>scale_ENG_S11)
stargazer<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">stargazer</span>(model1, model2, model4, type<span style="color:#333">=</span><span style="background-color:#fff0f0">&#34;text&#34;</span>)
</code></pre></div><pre><code>## 
## ==========================================================================================================
##                                                      Dependent variable:                                  
##                     --------------------------------------------------------------------------------------
##                                                           scale_G_SC                                      
##                                 (1)                          (2)                          (3)             
## ----------------------------------------------------------------------------------------------------------
## scale_MAT_S11                 0.644***                     0.390***                     0.264***          
##                               (0.007)                      (0.008)                      (0.008)           
##                                                                                                           
## scale_CR_S11                                               0.415***                     0.301***          
##                                                            (0.008)                      (0.008)           
##                                                                                                           
## scale_ENG_S11                                                                           0.331***          
##                                                                                         (0.008)           
##                                                                                                           
## Constant                       0.000                        0.000                        0.000            
##                               (0.007)                      (0.006)                      (0.006)           
##                                                                                                           
## ----------------------------------------------------------------------------------------------------------
## Observations                   12,411                       12,411                       12,411           
## R2                             0.415                        0.523                        0.585            
## Adjusted R2                    0.414                        0.523                        0.585            
## Residual Std. Error      0.765 (df = 12409)           0.691 (df = 12408)           0.644 (df = 12407)     
## F Statistic         8,785.839*** (df = 1; 12409) 6,799.872*** (df = 2; 12408) 5,834.986*** (df = 3; 12407)
## ==========================================================================================================
## Note:                                                                          *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01
</code></pre>
<p>Some outcomes from model 4:</p>
<ul>
<li>The Adjusted R squared has improved from 0.4145 to 0.523 and now to 0.585, meaning we can now explain more of variation in G_SC by including ENG_S11 into our model</li>
<li>ENG_S11 is statically significant to p&lt;0.01.</li>
</ul>
<p>One of the assumptions of a multiple linear regression model is that the residuals follow a normal distribution. We need to check this now on our model2. We can do this by finding any influential outliers by using cook’s distance.</p>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-62-1.png" alt="Cook's D for model4" width="672" /></p>
<p class="caption">
<p>Figure 20: Cook’s D for model4</p>
</p>
</div>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">influential <span style="color:#333">&lt;-</span> <span style="color:#06b;font-weight:bold">as.numeric</span>(<span style="color:#06b;font-weight:bold">names</span>(cooksd)<span style="color:#06b;font-weight:bold">[</span>(cooksd <span style="color:#333">&gt;</span> <span style="color:#60e;font-weight:bold">4</span><span style="color:#333">*</span><span style="color:#06b;font-weight:bold">mean</span>(cooksd, na.rm<span style="color:#333">=</span>T))])  <span style="color:#888"># influential row numbers</span>
<span style="color:#06b;font-weight:bold">cat</span>(<span style="background-color:#fff0f0">&#34;Number of influencers:&#34;</span>, <span style="color:#06b;font-weight:bold">length</span>(influential), <span style="background-color:#fff0f0">&#34;\n&#34;</span>)
</code></pre></div><pre><code>## Number of influencers: 584
</code></pre>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#06b;font-weight:bold">cat </span>(<span style="background-color:#fff0f0">&#34;20 influencers in MAT_S11&#34;</span>,<span style="color:#06b;font-weight:bold">head</span>(df[influential, ]<span style="color:#333">$</span>MAT_S11, n <span style="color:#333">=</span> <span style="color:#60e;font-weight:bold">20</span>),<span style="background-color:#fff0f0">&#34;\n&#34;</span>)
</code></pre></div><pre><code>## 20 influencers in MAT_S11 54 45 82 47 69 40 61 78 85 46 81 76 39 60 45 50 97 52 65 88
</code></pre>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#06b;font-weight:bold">cat </span>(<span style="background-color:#fff0f0">&#34;20 influencers in CR_S11&#34;</span>,<span style="color:#06b;font-weight:bold">head</span>(df[influential, ]<span style="color:#333">$</span>CR_S11, n <span style="color:#333">=</span> <span style="color:#60e;font-weight:bold">20</span>),<span style="background-color:#fff0f0">&#34;\n&#34;</span>)
</code></pre></div><pre><code>## 20 influencers in CR_S11 41 47 98 54 66 40 53 69 60 43 75 69 39 69 52 62 87 45 65 62
</code></pre>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#06b;font-weight:bold">cat </span>(<span style="background-color:#fff0f0">&#34;20 influencers in ENG_S11&#34;</span>,<span style="color:#06b;font-weight:bold">head</span>(df[influential, ]<span style="color:#333">$</span>ENG_S11, n <span style="color:#333">=</span> <span style="color:#60e;font-weight:bold">20</span>),<span style="background-color:#fff0f0">&#34;\n&#34;</span>)
</code></pre></div><pre><code>## 20 influencers in ENG_S11 52 54 58 46 85 53 52 67 70 53 85 90 43 67 32 76 95 46 44 48
</code></pre>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#06b;font-weight:bold">cat </span>(<span style="background-color:#fff0f0">&#34;Percentage of influencers: &#34;</span>, (<span style="color:#06b;font-weight:bold">length</span>(influential) <span style="color:#333">/</span> <span style="color:#06b;font-weight:bold">nrow</span>(df)) <span style="color:#333">*</span> <span style="color:#60e;font-weight:bold">100</span>, <span style="background-color:#fff0f0">&#34;% \n&#34;</span>)
</code></pre></div><pre><code>## Percentage of influencers:  4.705503 %
</code></pre>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-64-1.png" alt="Cook's D for model4" width="672" /></p>
<p class="caption">
<p>Figure 21: Cook’s D for model4</p>
</p>
</div>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-65-1.png" alt="Assess homocedasticity for model4" width="672" /></p>
<p class="caption">
<p>Figure 22: Assess homocedasticity for model4</p>
</p>
</div>
<ul>
<li>We can see there is absolutely no heteroscedastity, we see a completely random, equal distribution of points throughout the range of X axis and a flat red line. There is no pattern in the residuals.</li>
</ul>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-66-1.png" alt="Histogram and density plot of the residuals for model4" width="672" /></p>
<p class="caption">
<p>Figure 23: Histogram and density plot of the residuals for model4</p>
</p>
</div>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">residuals <span style="color:#333">&lt;-</span> <span style="color:#06b;font-weight:bold">residuals</span>(model3)
resids<span style="color:#333">&lt;-</span> <span style="color:#06b;font-weight:bold">abs</span>(residuals)
<span style="color:#06b;font-weight:bold">cat</span>(<span style="background-color:#fff0f0">&#34;Percentage greater than 1.96 SDs:&#34;</span>, FSA<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">perc</span>(<span style="color:#06b;font-weight:bold">as.numeric</span>(resids), <span style="color:#60e;font-weight:bold">1.96</span>, <span style="background-color:#fff0f0">&#34;gt&#34;</span>),<span style="background-color:#fff0f0">&#34;% \n&#34;</span>)
</code></pre></div><pre><code>## Percentage greater than 1.96 SDs: 0.8621384 %
</code></pre>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#06b;font-weight:bold">cat</span>(<span style="background-color:#fff0f0">&#34;Percentage greater than 3.29 SDs:&#34;</span>,FSA<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">perc</span>(<span style="color:#06b;font-weight:bold">as.numeric</span>(resids), <span style="color:#60e;font-weight:bold">3.29</span>, <span style="background-color:#fff0f0">&#34;gt&#34;</span>), <span style="background-color:#fff0f0">&#34;%&#34;</span>)
</code></pre></div><pre><code>## Percentage greater than 3.29 SDs: 0.0402868 %
</code></pre>
<ul>
<li>almost 0% outliers at 3.29 standards deviations from mean and for a data set this size. We can accept the distribution as normal.</li>
</ul>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-68-1.png" alt="QQ plot of the residuals for model4" width="672" /></p>
<p class="caption">
<p>Figure 24: QQ plot of the residuals for model4</p>
</p>
</div>
<pre><code>## [1] 1336 7721
</code></pre>
<h3 id="collinearity-2">Collinearity:</h3>
<p>Calculate Collinearity:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">vifmodel<span style="color:#333">&lt;-</span>car<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">vif</span>(model4)
vifmodel
</code></pre></div><pre><code>## df$scale_MAT_S11  df$scale_CR_S11 df$scale_ENG_S11 
##         1.849495         1.803992         1.753561
</code></pre>
<ul>
<li>As a rule of thumb, a VIF score over 5 is a problem. A score over 10 should be remedied and you should consider dropping the problematic variable from the regression model</li>
</ul>
<p>Calculate tolerance:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#60e;font-weight:bold">1</span><span style="color:#333">/</span>vifmodel
</code></pre></div><pre><code>## df$scale_MAT_S11  df$scale_CR_S11 df$scale_ENG_S11 
##        0.5406883        0.5543261        0.5702683
</code></pre>
<ul>
<li>
<p>If the VIF value is greater than 2.5 or the Tolerance is less than 0.4, then you have concerns over multicollinearity.</p>
</li>
<li>
<p>Collinearity occurs when two or more independent variables are giving the same information, one could be redundant.</p>
</li>
<li>
<p>To check collinearity, we examine the correlation matrix that compares the independent variables with each other.</p>
</li>
<li>
<p>If we get a correlation coefficient of above 0.8, then we may have collinearity.</p>
</li>
</ul>
<div class="figure" style="text-align: center">
<p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-71-1.png" alt="correlation matrix for model4" width="672" /></p>
<p class="caption">
<p>Figure 25: correlation matrix for model4</p>
</p>
</div>
<ul>
<li>the result from our correlation matrix for model4 show that these variables have a correlation less than 0.8, so we don’t have collinearity.</li>
</ul>
<p>Reporting:</p>
<blockquote class="blockquote">
<p>Tests to see if the data met the assumption of collinearity indicated that multicollinearity was not a concern (MAT_S11, Tolerance = .63, VIF = 1.6; CR_S11, Tolerance = .63 VIF = 1.6; ENG_S11, Tolerance = .57 VIF = 1.7).</p>
</blockquote>
<h3 id="reporting-my-model-1">Reporting my model</h3>
<blockquote class="blockquote">
<p>A multiple regression analysis was conducted to determine if a student’s high school Mathematics (MAT_S11) score,high school Critical Reading (CR_S11) and English (ENG_S11) scores could predict a student’s Overall average score (G_SC) in Engineering in college.</p>
<p>Examination of the histogram, normal Q-Q plots of standardized residuals and the scatterplot of the dependent variable, academic satisfaction, and standardized residuals showed that the some outliers existed. However, examination of the standardized residuals showed that none could be considered to have undue influence (95% within limits of -3.29 to plus 3.29 and less than 5% with a Cook’s distance three times the mean.</p>
<p>Examination for multicollinearity showed that the tolerance and variance influence factor measures were within acceptable levels (tolerance &gt;0.4, VIF &lt;2.5 ) as outlined in Tarling (2008). The scatterplot of standardized residuals showed that the data met the assumptions of homogeneity of variance and linearity. The data also meets the assumption of non-zero variances of the predictors.</p>
</blockquote>
<p>The z-scale standardized equation of model4 is:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r"><span style="color:#06b;font-weight:bold">coef</span>(model4)
</code></pre></div><pre><code>##             (Intercept)        df$scale_MAT_S11         df$scale_CR_S11 
## 0.000000000000001380494 0.263880736301899343488 0.300575704588454950539 
##        df$scale_ENG_S11 
## 0.330537537075545562182
</code></pre>
<pre><code> G_SC = 0 + 0.26 * MAT_S11 + 0.3 * CR_S11 + 0.3 * _ENG_S11
</code></pre><ul>
<li>explaining 58.5% of the variation in G_SC</li>
</ul>
<p>This would mean a student who achieves a mean score for MAT_S11, CR_S11 and ENG_S11 would get a z-scaled G_SC results which is also the mean score for G_SC:</p>
<pre><code> G_SC = 0 + 0.26 * 0 + 0.3 * 0 + 0.3 * 0 = 0 
</code></pre><p>A student who achieves a score 1 standard deviation above mean for those three subjects will achieve a score which less than one stanard deviation above the mean in G_SC, thus we can see that more variables are also responsible for thhis G_SC variation:</p>
<pre><code> G_SC = 0 + 0.26 * 1 + 0.3 * 1 + 0.3 * 1 = 0.86
</code></pre><h2 id="differential-effect">Differential effect</h2>
<p>I tried to include the variables which were ordinal and nominal into my model however the both failed Levene’s Test for Homogeneity of Variance.</p>
<p>I will try to include COMPUTER into my model as a differential variable. Let’s check out that variable:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">df <span style="color:#333">%&gt;%</span>
  <span style="color:#06b;font-weight:bold">ggplot</span>(<span style="color:#06b;font-weight:bold">aes</span>(x<span style="color:#333">=</span>COMPUTER, y<span style="color:#333">=</span>G_SC, fill<span style="color:#333">=</span>COMPUTER)) <span style="color:#333">+</span>
    <span style="color:#06b;font-weight:bold">geom_boxplot</span>() <span style="color:#333">+</span>
    <span style="color:#06b;font-weight:bold">scale_fill_viridis</span>(discrete <span style="color:#333">=</span> <span style="color:#080;font-weight:bold">TRUE</span>, alpha<span style="color:#333">=</span><span style="color:#60e;font-weight:bold">0.6</span>) <span style="color:#333">+</span>
    <span style="color:#06b;font-weight:bold">geom_jitter</span>(color<span style="color:#333">=</span><span style="background-color:#fff0f0">&#34;black&#34;</span>, size<span style="color:#333">=</span><span style="color:#60e;font-weight:bold">0.4</span>, alpha<span style="color:#333">=</span><span style="color:#60e;font-weight:bold">0.9</span>) <span style="color:#333">+</span>
    <span style="color:#06b;font-weight:bold">ggtitle</span>(<span style="background-color:#fff0f0">&#34;A boxplot with COMPUTER and the Overall average score (G_SC)&#34;</span>) <span style="color:#333">+</span>
    <span style="color:#06b;font-weight:bold">ylab</span>(<span style="background-color:#fff0f0">&#34;Overall average score (G_SC) &#34;</span>)
</code></pre></div><p><img src="/blog/posts/academicperf/index_files/figure-html/unnamed-chunk-73-1.png" width="672" /></p>
<p>stats for COMPUTER:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">psych<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">describeBy</span>(df<span style="color:#333">$</span>G_SC, df<span style="color:#333">$</span>COMPUTER, mat<span style="color:#333">=</span><span style="color:#080;font-weight:bold">TRUE</span>)
</code></pre></div><pre><code>##     item group1 vars     n     mean       sd median  trimmed     mad min max
## X11    1     No    1  2237 155.9526 21.86040    156 156.0815 22.2390  76 226
## X12    2    Yes    1 10174 164.1964 23.11635    165 164.4912 23.7216  37 247
##     range        skew    kurtosis        se
## X11   150 -0.07375166 -0.02764496 0.4621948
## X12   210 -0.11780745 -0.07145279 0.2291782
</code></pre>
<p>Checking again for Levene’s Test for Homogeneity of Variance:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">car<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">leveneTest</span>(G_SC <span style="color:#333">~</span> COMPUTER, data<span style="color:#333">=</span>df)
</code></pre></div><pre><code>## Warning in leveneTest.default(y = y, group = group, ...): group coerced to
## factor.

## Levene's Test for Homogeneity of Variance (center = median)
##          Df F value    Pr(&gt;F)    
## group     1  13.994 0.0001842 ***
##       12409                      
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
</code></pre>
<p>Again this variable is failing Levene’s Test for Homogeneity of Variance.</p>
<p>We will go ahead and include it to see if it may be useful in our model. First we need a dummy variable for COMPUTER:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">df <span style="color:#333">&lt;-</span> df <span style="color:#333">%&gt;%</span>
  <span style="color:#06b;font-weight:bold">mutate</span>(dummy_COMPUTER <span style="color:#333">=</span> <span style="color:#06b;font-weight:bold">if_else</span>(COMPUTER <span style="color:#333">==</span> <span style="background-color:#fff0f0">&#34;Yes&#34;</span>,<span style="color:#60e;font-weight:bold">1</span>, <span style="color:#60e;font-weight:bold">0</span>))
</code></pre></div><p>stats for dummy_COMPUTER:</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">psych<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">describeBy</span>(df<span style="color:#333">$</span>G_SC, df<span style="color:#333">$</span>dummy_COMPUTER, mat<span style="color:#333">=</span><span style="color:#080;font-weight:bold">TRUE</span>)
</code></pre></div><pre><code>##     item group1 vars     n     mean       sd median  trimmed     mad min max
## X11    1      0    1  2237 155.9526 21.86040    156 156.0815 22.2390  76 226
## X12    2      1    1 10174 164.1964 23.11635    165 164.4912 23.7216  37 247
##     range        skew    kurtosis        se
## X11   150 -0.07375166 -0.02764496 0.4621948
## X12   210 -0.11780745 -0.07145279 0.2291782
</code></pre>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">userfriendlyscience<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">oneway</span>(<span style="color:#06b;font-weight:bold">as.factor</span>(df<span style="color:#333">$</span>dummy_COMPUTER),y<span style="color:#333">=</span>df<span style="color:#333">$</span>G_SC,posthoc<span style="color:#333">=</span><span style="background-color:#fff0f0">&#39;Tukey&#39;</span>)
</code></pre></div><pre><code>## Registered S3 methods overwritten by 'lme4':
##   method                          from
##   cooks.distance.influence.merMod car 
##   influence.merMod                car 
##   dfbeta.influence.merMod         car 
##   dfbetas.influence.merMod        car

## ### Oneway Anova for y=G_SC and x=dummy_COMPUTER (groups: 0, 1)

## Registered S3 methods overwritten by 'ufs':
##   method                     from               
##   grid.draw.ggProportionPlot userfriendlyscience
##   pander.associationMatrix   userfriendlyscience
##   pander.dataShape           userfriendlyscience
##   pander.descr               userfriendlyscience
##   pander.normalityAssessment userfriendlyscience
##   print.CramersV             userfriendlyscience
##   print.associationMatrix    userfriendlyscience
##   print.confIntOmegaSq       userfriendlyscience
##   print.confIntV             userfriendlyscience
##   print.dataShape            userfriendlyscience
##   print.descr                userfriendlyscience
##   print.ggProportionPlot     userfriendlyscience
##   print.meanConfInt          userfriendlyscience
##   print.multiVarFreq         userfriendlyscience
##   print.normalityAssessment  userfriendlyscience
##   print.regrInfluential      userfriendlyscience
##   print.scaleDiagnosis       userfriendlyscience
##   print.scaleStructure       userfriendlyscience
##   print.scatterMatrix        userfriendlyscience

## Omega squared: 95% CI = [.01; .02], point estimate = .02
## Eta Squared: 95% CI = [.02; .02], point estimate = .02
## 
##                                        SS    Df        MS      F     p
## Between groups (error + effect) 124624.22     1 124624.22 237.75 &lt;.001
## Within groups (error only)      6504632.6 12409    524.19             
## 
## 
## ### Post hoc test: Tukey
## 
##     diff lwr upr  p adj
## 1-0 8.24 7.2 9.29 &lt;.001
</code></pre>
<p>Reporting the results with eta squared effect:</p>
<blockquote class="blockquote">
<p>A one-way between-groups analysis of variance (ANOVA) was conducted to explore the impact of having a computer, as measured by the overall engineering scores. Participants were divided into two groups, one with a computer and one without. There was a statistically significant difference at the p &lt; .05 level in G_SC scores for the two groups: (F(1, 12409)= 237.75, p&lt;0.05. Despite reaching statistical significance, the actual difference in mean scores between groups was quite small. The effect size, calculated using eta squared was (0.02). Post-hoc comparisons using the Tukey HSD test indicated that the mean score for Group 1 (M=155.9, SD=21.8) was significantly different to that for Group 2 (M=164.19, SD=23.12).</p>
</blockquote>
<p>Creating a new model5 with dummy_COMPUTER</p>
<div class="highlight"><pre style="background-color:#fff;-moz-tab-size:4;-o-tab-size:4;tab-size:4"><code class="language-r" data-lang="r">model5<span style="color:#333">&lt;-</span><span style="color:#06b;font-weight:bold">lm</span>(df<span style="color:#333">$</span>scale_G_SC<span style="color:#333">~</span>df<span style="color:#333">$</span>scale_MAT_S11<span style="color:#333">+</span>df<span style="color:#333">$</span>scale_CR_S11<span style="color:#333">+</span>df<span style="color:#333">$</span>scale_ENG_S11<span style="color:#333">+</span>df<span style="color:#333">$</span>dummy_COMPUTER)
stargazer<span style="color:#333">::</span><span style="color:#06b;font-weight:bold">stargazer</span>(model1, model4, model5, type<span style="color:#333">=</span><span style="background-color:#fff0f0">&#34;text&#34;</span>)
</code></pre></div><pre><code>## 
## ==========================================================================================================
##                                                      Dependent variable:                                  
##                     --------------------------------------------------------------------------------------
##                                                           scale_G_SC                                      
##                                 (1)                          (2)                          (3)             
## ----------------------------------------------------------------------------------------------------------
## scale_MAT_S11                 0.644***                     0.264***                     0.264***          
##                               (0.007)                      (0.008)                      (0.008)           
##                                                                                                           
## scale_CR_S11                                               0.301***                     0.301***          
##                                                            (0.008)                      (0.008)           
##                                                                                                           
## scale_ENG_S11                                              0.331***                     0.329***          
##                                                            (0.008)                      (0.008)           
##                                                                                                           
## dummy_COMPUTER                                                                           0.021            
##                                                                                         (0.015)           
##                                                                                                           
## Constant                       0.000                        0.000                        -0.017           
##                               (0.007)                      (0.006)                      (0.014)           
##                                                                                                           
## ----------------------------------------------------------------------------------------------------------
## Observations                   12,411                       12,411                       12,411           
## R2                             0.415                        0.585                        0.585            
## Adjusted R2                    0.414                        0.585                        0.585            
## Residual Std. Error      0.765 (df = 12409)           0.644 (df = 12407)           0.644 (df = 12406)     
## F Statistic         8,785.839*** (df = 1; 12409) 5,834.986*** (df = 3; 12407) 4,377.053*** (df = 4; 12406)
## ==========================================================================================================
## Note:                                                                          *p&lt;0.1; **p&lt;0.05; ***p&lt;0.01
</code></pre>
<ul>
<li>Adding the dummy_COMPUTER is not statisically significant</li>
</ul>
<h1 id="discussionconclusion">Discussion/Conclusion</h1>
<h1 id="references">References</h1>
<div id="refs" class="references">
<div id="ref-stephanie_2018">
<p>Stephanie. 2018. “Cook’s Distance / Cook’s d: Definition, Interpretation.” <em>Statistics How To</em>. <a href="https://www.statisticshowto.com/cooks-distance/">https://www.statisticshowto.com/cooks-distance/</a>.</p>
</div>
</div>

        </div>

        
        
      <hr />
        <div class="row next-prev-navigator">


  

  
    
    
      
        
        
        <div class="col-md-12 next-article">
          <a href="/blog/posts/studentperf/" class="btn btn-outline-info">
            <span>Next <i class="fas fa-chevron-circle-right"></i></span>
            <br />
            <span>Secondary School Student Performance</span>
          </a>
        </div>
      
    
  

</div>

      <hr />
      
      
          

      
      </div>
    </div>
  </div>
  
</section>


      
      
  <section class="toc-section" id="toc-section">
    
    <div class="toc-holder">
      <h5 class="text-center pl-3">Table of Contents</h5>
      <hr>
      <div class="toc">
        <nav id="TableOfContents">
  <ol>
    <li><a href="#research-question">Research Question</a></li>
    <li><a href="#dataset">Dataset</a>
      <ol>
        <li><a href="#exploring-variables-in-research-question">Exploring variables in research question</a>
          <ol>
            <li><a href="#mathematics-mat_s11">Mathematics (MAT_S11)</a></li>
            <li><a href="#critical-reading-cr_s11">Critical Reading (CR_S11)</a></li>
            <li><a href="#english-eng_s11">English (ENG_S11)</a></li>
            <li><a href="#gender-variable">Gender variable</a></li>
            <li><a href="#school-variable">School variable</a></li>
            <li><a href="#biology-bio_s11">Biology (BIO_S11)</a></li>
            <li><a href="#revenue-variable">REVENUE variable</a></li>
            <li><a href="#school-variable-1">School variable</a></li>
          </ol>
        </li>
      </ol>
    </li>
    <li><a href="#results">Results</a>
      <ol>
        <li><a href="#statistical-evidence">Statistical Evidence</a>
          <ol>
            <li><a href="#simple-linear-regression">Simple Linear Regression</a></li>
          </ol>
        </li>
        <li><a href="#mulpile-linear-regression">Mulpile Linear Regression</a>
          <ol>
            <li><a href="#collinearity">Collinearity:</a></li>
            <li><a href="#muliple-lienar-regression-checks">Muliple Lienar regression checks</a></li>
            <li><a href="#reporting-my-model">Reporting my model</a></li>
          </ol>
        </li>
        <li><a href="#adding-gender">Adding GENDER</a></li>
        <li><a href="#adding-school_nat">Adding SCHOOL_NAT</a></li>
        <li><a href="#adding-biology-bio_s11">Adding Biology (BIO_S11)</a>
          <ol>
            <li><a href="#collinearity-1">Collinearity:</a></li>
          </ol>
        </li>
        <li><a href="#adding-revenue">Adding REVENUE</a></li>
        <li><a href="#adding-english-eng_s11">Adding English (ENG_S11)</a>
          <ol>
            <li><a href="#collinearity-2">Collinearity:</a></li>
            <li><a href="#reporting-my-model-1">Reporting my model</a></li>
          </ol>
        </li>
        <li><a href="#differential-effect">Differential effect</a></li>
      </ol>
    </li>
    <li><a href="#discussionconclusion">Discussion/Conclusion</a></li>
    <li><a href="#references">References</a></li>
  </ol>
</nav>
      </div>
    </div>
    
  </section>

    </div>

    

  




  




  
  
    
  


<footer class="container-fluid text-center align-content-center footer pb-2">
  <div class="container pt-5">
    <div class="row text-left">
      <div class="col-md-4 col-sm-12">
        <h5>Navigation</h5>
        
        <ul>
            
              
              
                
              
              <li class="nav-item">
                <a class="smooth-scroll" href="#about">About</a>
              </li>
            
            
              
              
                
              
              <li class="nav-item">
                <a class="smooth-scroll" href="#recent-posts">Recent Posts</a>
              </li>
            
        </ul>
        

      </div>
      
      <div class="col-md-4 col-sm-12">
        <h5></h5>
        <ul>
          
        </ul>
      </div>
      
      
    </div>
  </div>
  <hr />
  <div class="container">
    <div class="row text-left">
      <div class="col-md-4">
        <a id="theme" href="https://github.com/hossainemruz/toha" target="#">
          <img src="/blog/assets/images/inverted-logo.png">
          Toha
        </a>
      </div>
      <div class="col-md-4 text-center">© 2021 Copyright.</div>
      <div class="col-md-4 text-right">
        <a id="hugo" href="https://gohugo.io/">Powered by
        <img
          src="/blog/assets/images/hugo-logo-wide.svg"
          alt="Hugo Logo"
          height="18"
        />
        </a>
      </div>
    </div>
  </div>
</footer>

    <script src="/blog/assets/js/jquery-3.4.1.min.js"></script>
<script src="/blog/assets/js/popper.min.js"></script>
<script src="/blog/assets/js/bootstrap.min.js"></script>

<script src="/blog/assets/js/navbar.js"></script>
<script src="/blog/assets/js/main.js"></script>


    
    
<script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.18.1/highlight.min.js"></script>
<script src="/blog/assets/js/single.js"></script>
<script>
  hljs.initHighlightingOnLoad();
</script>


  </body>
</html>
